apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-system

commonLabels:
  environment: staging
  app.kubernetes.io/instance: staging

resources:
  - ../../base

configMapGenerator:
  - name: etradie-envoy-config
    namespace: envoy-system
    behavior: replace
    files:
      - envoy.yaml=../../../../../src/envoy/config/staging/envoy-staging.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: patches/replicas.yaml
  - target:
      kind: Deployment
      name: etradie-envoy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
  - target:
      kind: HorizontalPodAutoscaler
      name: etradie-envoy
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 6
  - target:
      kind: ServiceMonitor
      name: etradie-envoy
    patch: |-
      - op: replace
        path: /spec/endpoints/0/interval
        value: "15s"

images:
  - name: envoyproxy/envoy
    newTag: v1.28.0

replicas:
  - name: etradie-envoy
    count: 3
