apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-ingress
spec:
  replicas: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-ingress
spec:
  minReplicas: 10
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: edge_ingress_active_connections
        target:
          type: AverageValue
          averageValue: "8000"
