import type { TradingPlan } from '../../types';

interface Props {
  plan: TradingPlan;
}

function formatDate(iso: string): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

function formatBalance(plan: TradingPlan): string {
  const ccy = plan.balance_currency || 'USD';
  try {
    return `${ccy} ${plan.balance_used.toLocaleString()}`;
  } catch {
    return `${ccy} ${plan.balance_used}`;
  }
}

/**
 * "Generated By Exoper AI" footer block. PRACTICE.md requires every
 * plan to carry generation_date, profile_summary, and version_id so
 * the user (and a future progression-analytics surface) can compare
 * plan evolution over time.
 */
export function FooterMetadata({ plan }: Props) {
  return (
    <section className="rounded-2xl border border-dashed border-black/10 dark:border-white/10 bg-black/[0.01] dark:bg-white/[0.02] p-6 text-center sm:text-left">
      <p className="text-[10px] font-black uppercase tracking-[0.2em] text-brand">
        Generated by {plan.generated_by || 'Exoper AI'}
      </p>
      {plan.profile_summary && (
        <p className="mt-2 text-xs font-medium text-black/60 dark:text-white/60 leading-relaxed italic">{plan.profile_summary}</p>
      )}
      <dl className="mt-6 grid grid-cols-1 gap-x-6 gap-y-3 text-[10px] font-black uppercase tracking-widest text-black/20 dark:text-white/20 sm:grid-cols-2 lg:grid-cols-4">
        <div className="flex flex-col gap-1">
          <dt>Generated at</dt>
          <dd className="text-black/40 dark:text-white/40">{formatDate(plan.generated_at)}</dd>
        </div>
        <div className="flex flex-col gap-1">
          <dt>Trading system version</dt>
          <dd className="text-black/40 dark:text-white/40 tabular-nums">v{plan.profile_version}</dd>
        </div>
        <div className="flex flex-col gap-1">
          <dt>Account balance used</dt>
          <dd className="text-black/40 dark:text-white/40 tabular-nums">{formatBalance(plan)}</dd>
        </div>
        <div className="flex flex-col gap-1">
          <dt>Balance source</dt>
          <dd className="text-black/40 dark:text-white/40 capitalize">
            {plan.balance_source_kind}
          </dd>
        </div>
      </dl>
    </section>
  );
}
