import type { TradingPlan } from '../../types';

interface Props {
  plan: TradingPlan;
}

function formatDate(iso: string): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

function formatBalance(plan: TradingPlan): string {
  const ccy = plan.balance_currency || 'USD';
  try {
    return `${ccy} ${plan.balance_used.toLocaleString()}`;
  } catch {
    return `${ccy} ${plan.balance_used}`;
  }
}

/**
 * "Generated By Exoper AI" footer block. PRACTICE.md requires every
 * plan to carry generation_date, profile_summary, and version_id so
 * the user (and a future progression-analytics surface) can compare
 * plan evolution over time.
 */
export function FooterMetadata({ plan }: Props) {
  return (
    <section className="rounded-lg border border-dashed border-border bg-app p-4 sm:p-5">
      <p className="text-xs font-semibold uppercase tracking-widest text-brand">
        Generated by {plan.generated_by || 'Exoper AI'}
      </p>
      {plan.profile_summary && (
        <p className="mt-2 text-sm text-content-secondary">{plan.profile_summary}</p>
      )}
      <dl className="mt-3 grid grid-cols-1 gap-x-6 gap-y-1 text-xs text-content-muted sm:grid-cols-2">
        <div>
          <dt className="inline">Generated at: </dt>
          <dd className="inline text-content">{formatDate(plan.generated_at)}</dd>
        </div>
        <div>
          <dt className="inline">Trading system version: </dt>
          <dd className="inline text-content tabular-nums">{plan.profile_version}</dd>
        </div>
        <div>
          <dt className="inline">Account balance used: </dt>
          <dd className="inline text-content tabular-nums">{formatBalance(plan)}</dd>
        </div>
        <div>
          <dt className="inline">Balance source: </dt>
          <dd className="inline text-content capitalize">
            {plan.balance_source_kind}
          </dd>
        </div>
      </dl>
    </section>
  );
}
