apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maxmind-credentials
  namespace: etradie-system
  labels:
    app.kubernetes.io/name: edge-ingress
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: etradie
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: maxmind-credentials
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: etradie/services/edge-ingress/maxmind
        property: license_key
    - secretKey: account-id
      remoteRef:
        key: etradie/services/edge-ingress/maxmind
        property: account_id
