apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-ingress
  namespace: etradie-system
  labels:
    app.kubernetes.io/name: edge-ingress
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: etradie
automountServiceAccountToken: false
