import type { CompositeJournalRow, TradingPlan } from '../types';

/**
 * Zero-dependency Excel export.
 *
 * Emits a SpreadsheetML 2003 XML workbook (.xls extension). Excel,
 * Google Sheets, Numbers, and LibreOffice all open this format
 * natively. The alternative — xlsx-writer or sheetjs — adds 500-700
 * KB of dependency to the bundle for what is fundamentally a
 * read-once download artefact, so we hand-roll the XML.
 *
 * Workbook structure mirrors PRACTICE.md sections:
 *
 *   Sheet 1 — Trader Profile     (headline + bullets)
 *   Sheet 2 — Account Parameters (parameter / value table)
 *   Sheet 3 — Daily Journal      (25-column journal table)
 *   Sheet 4 — Weekly Review      (numbered reflection prompts)
 *   Sheet 5 — Discipline         (metric / score table)
 *   Sheet 6 — Objectives         (numbered objectives)
 *   Sheet 7 — Footer             (Generated By Exoper AI metadata)
 *
 * Every cell is emitted as a String to avoid Excel's aggressive
 * number-coercion ("01/02" -> a date, "1:4" -> a time, etc.).
 */

// XML special chars that must be escaped in attribute and text data.
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function cell(value: string | number | null | undefined): string {
  const s = value == null ? '' : String(value);
  return `<Cell><Data ss:Type="String">${xmlEscape(s)}</Data></Cell>`;
}

function row(cells: Array<string | number | null | undefined>): string {
  return `<Row>${cells.map(cell).join('')}</Row>`;
}

function sheet(name: string, rows: string[]): string {
  const safeName = name.replace(/[\\\/\?\*\[\]:]/g, '').slice(0, 31);
  return (
    `<Worksheet ss:Name="${xmlEscape(safeName)}">` +
    `<Table>${rows.join('')}</Table>` +
    `</Worksheet>`
  );
}

function formatGenerated(plan: TradingPlan): string {
  if (!plan.generated_at) return '';
  try {
    return new Date(plan.generated_at).toLocaleString();
  } catch {
    return plan.generated_at;
  }
}

function buildWorkbookXML(plan: TradingPlan): string {
  // -- Sheet 1: Trader Profile --------------------------------------
  const profileRows: string[] = [
    row(['Trader Profile']),
    row([plan.trader_profile.headline]),
    row([]),
    row(['Highlights']),
    ...plan.trader_profile.bullets.map((b) => row([`• ${b}`])),
  ];

  // -- Sheet 2: Account Parameters ----------------------------------
  const a = plan.account;
  const accountRows: string[] = [
    row(['Parameter', 'Value']),
    row(['Starting Balance', a.starting_balance]),
    row(['Max Daily Risk', a.max_daily_risk]),
    row(['Max Weekly Drawdown', a.max_weekly_drawdown]),
    row(['Preferred RR', a.preferred_rr]),
    row(['Max Trades Per Day', a.max_trades_per_day]),
    row(['Trading Days Per Week', a.trading_days_per_week]),
  ];

  // -- Sheet 3: Daily Journal ---------------------------------------
  // 25 columns, exactly mirroring PRACTICE.md's final spec.
  const journalRows: string[] = [
    row([
      'Date',
      'Session',
      'Pair',
      'Direction',
      'Style',
      'Setup Type',
      'HTF Bias',
      'Entry',
      'Stop Loss',
      'Take Profit',
      'Risk %',
      'Position Size',
      'Exit',
      'RR Planned',
      'RR Achieved',
      'P&L',
      'Outcome',
      'Rule Followed?',
      'Emotion Before Trade',
      'Emotion After Trade',
      'Trade Quality',
      'Mistake Category',
      'News Present?',
      'Screenshot Link',
      'Notes',
    ]),
    ...plan.journal.map((j) =>
      row([
        j.date,
        j.session,
        j.pair,
        j.direction,
        j.style,
        j.setup_type,
        j.htf_bias,
        j.entry,
        j.stop_loss,
        j.take_profit,
        j.risk_percent,
        j.position_size,
        j.exit,
        j.rr_planned,
        j.rr_achieved,
        j.pnl,
        j.outcome,
        j.rule_followed,
        j.emotion_before_trade,
        j.emotion_after_trade,
        j.trade_quality,
        j.mistake_category,
        j.news_present,
        j.screenshot_link,
        j.notes,
      ]),
    ),
  ];

  // -- Sheet 4: Weekly Review ---------------------------------------
  const reviewRows: string[] = [
    row(['#', 'Reflection Prompt', 'Answer']),
    ...plan.weekly_review.prompts.map((p, i) => row([`${i + 1}`, p, ''])),
  ];

  // -- Sheet 5: Discipline Scorecard --------------------------------
  const scorecardRows: string[] = [
    row(['Metric', 'Score (X/10)']),
    ...plan.scorecard.items.map((it) => row([it.metric, it.score])),
  ];

  // -- Sheet 6: Objectives ------------------------------------------
  const objectivesRows: string[] = [
    row(['#', 'Objective']),
    ...plan.objectives.items.map((o, i) => row([`${i + 1}`, o])),
  ];

  // -- Sheet 7: Footer ----------------------------------------------
  const footerRows: string[] = [
    row(['Generated By', plan.generated_by]),
    row(['Generated At', formatGenerated(plan)]),
    row(['Schema Version', plan.schema_version]),
    row(['Trader Profile Summary', plan.profile_summary]),
    row(['Trading System Version', plan.profile_version]),
    row([
      'Account Balance Used',
      `${plan.balance_currency} ${plan.balance_used.toLocaleString()}`,
    ]),
    row(['Balance Source', plan.balance_source_kind]),
  ];

  return (
    `<?xml version="1.0"?>` +
    `<?mso-application progid="Excel.Sheet"?>` +
    `<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" ` +
    `xmlns:o="urn:schemas-microsoft-com:office:office" ` +
    `xmlns:x="urn:schemas-microsoft-com:office:excel" ` +
    `xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">` +
    sheet('Trader Profile', profileRows) +
    sheet('Account', accountRows) +
    sheet('Daily Journal', journalRows) +
    sheet('Weekly Review', reviewRows) +
    sheet('Discipline', scorecardRows) +
    sheet('Objectives', objectivesRows) +
    sheet('Footer', footerRows) +
    `</Workbook>`
  );
}

/**
 * Build a single-sheet SpreadsheetML workbook for the auto-populated
 * Daily Execution Journal composite. Objective cells are already
 * formatted by the gateway (design §7); subjective cells come from the
 * trader's saved annotations. The internal trade_id join key is
 * deliberately omitted from the printed sheet (design §9); a Status
 * column makes Open vs Closed unambiguous in the export.
 */
function buildJournalWorkbookXML(rows: CompositeJournalRow[]): string {
  const journalRows: string[] = [
    row([
      'Status',
      'Date',
      'Session',
      'Pair',
      'Direction',
      'Style',
      'Setup Type',
      'HTF Bias',
      'Entry',
      'Stop Loss',
      'Take Profit',
      'Risk %',
      'Position Size',
      'Exit',
      'RR Planned',
      'RR Achieved',
      'P&L',
      'Outcome',
      'Rule Followed?',
      'Emotion Before Trade',
      'Emotion After Trade',
      'Trade Quality',
      'Mistake Category',
      'News Present?',
      'Screenshot Link',
      'Notes',
    ]),
    ...rows.map((r) =>
      row([
        r.is_open ? 'Open' : 'Closed',
        r.date,
        r.session,
        r.pair,
        r.direction,
        r.style,
        r.setup_type,
        r.htf_bias,
        r.entry,
        r.stop_loss,
        r.take_profit,
        r.risk_percent,
        r.position_size,
        r.exit,
        r.rr_planned,
        r.rr_achieved,
        r.pnl,
        r.outcome,
        r.rule_followed,
        r.emotion_before_trade,
        r.emotion_after_trade,
        r.trade_quality,
        r.mistake_category,
        r.news_present,
        r.screenshot_link,
        r.notes,
      ]),
    ),
  ];

  return (
    `<?xml version="1.0"?>` +
    `<?mso-application progid="Excel.Sheet"?>` +
    `<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" ` +
    `xmlns:o="urn:schemas-microsoft-com:office:office" ` +
    `xmlns:x="urn:schemas-microsoft-com:office:excel" ` +
    `xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">` +
    sheet('Daily Journal', journalRows) +
    `</Workbook>`
  );
}

/**
 * Trigger a browser download of the auto-populated Daily Execution
 * Journal composite as a SpreadsheetML 2003 workbook (.xls). Returns
 * the chosen file name so callers can show it in a toast.
 */
export function downloadJournalAsExcel(rows: CompositeJournalRow[]): string {
  const xml = buildJournalWorkbookXML(rows);
  const blob = new Blob([xml], {
    type: 'application/vnd.ms-excel;charset=utf-8',
  });

  const stamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .replace(/T/, '_')
    .slice(0, 19);
  const filename = `Exoper-Daily-Journal-${stamp}.xls`;

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(url), 1000);

  return filename;
}

/**
 * Trigger a browser download of the plan as a SpreadsheetML 2003
 * workbook (.xls). The MIME type “application/vnd.ms-excel” is the
 * de-facto handler for this format across operating systems.
 *
 * Returns the chosen file name so callers can show it in a toast.
 */
export function downloadPlanAsExcel(plan: TradingPlan): string {
  const xml = buildWorkbookXML(plan);
  const blob = new Blob([xml], {
    type: 'application/vnd.ms-excel;charset=utf-8',
  });

  const stamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .replace(/T/, '_')
    .slice(0, 19);
  const filename = `Exoper-Trading-Plan-${stamp}.xls`;

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  // Defer revoke so Safari has time to read the blob before we free it.
  setTimeout(() => URL.revokeObjectURL(url), 1000);

  return filename;
}
