// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCycleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Symbols to analyse. If empty, uses the active symbol selection.
	Symbols       []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	TraceId       string   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCycleRequest) Reset() {
	*x = RunCycleRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCycleRequest) ProtoMessage() {}

func (x *RunCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCycleRequest.ProtoReflect.Descriptor instead.
func (*RunCycleRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RunCycleRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *RunCycleRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CycleOutput struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CycleStatus  string                 `protobuf:"bytes,1,opt,name=cycle_status,json=cycleStatus,proto3" json:"cycle_status,omitempty"`
	CycleOutcome string                 `protobuf:"bytes,2,opt,name=cycle_outcome,json=cycleOutcome,proto3" json:"cycle_outcome,omitempty"`
	PhaseReached string                 `protobuf:"bytes,3,opt,name=phase_reached,json=phaseReached,proto3" json:"phase_reached,omitempty"`
	Symbol       string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	DurationMs   float64                `protobuf:"fixed64,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TraceId      string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Error        string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ErrorStage   string                 `protobuf:"bytes,8,opt,name=error_stage,json=errorStage,proto3" json:"error_stage,omitempty"`
	// Full processor output, guard result, and execution result as JSON.
	ProcessorOutputJson []byte `protobuf:"bytes,9,opt,name=processor_output_json,json=processorOutputJson,proto3" json:"processor_output_json,omitempty"`
	GuardResultJson     []byte `protobuf:"bytes,10,opt,name=guard_result_json,json=guardResultJson,proto3" json:"guard_result_json,omitempty"`
	ExecutionResultJson []byte `protobuf:"bytes,11,opt,name=execution_result_json,json=executionResultJson,proto3" json:"execution_result_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CycleOutput) Reset() {
	*x = CycleOutput{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CycleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleOutput) ProtoMessage() {}

func (x *CycleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleOutput.ProtoReflect.Descriptor instead.
func (*CycleOutput) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CycleOutput) GetCycleStatus() string {
	if x != nil {
		return x.CycleStatus
	}
	return ""
}

func (x *CycleOutput) GetCycleOutcome() string {
	if x != nil {
		return x.CycleOutcome
	}
	return ""
}

func (x *CycleOutput) GetPhaseReached() string {
	if x != nil {
		return x.PhaseReached
	}
	return ""
}

func (x *CycleOutput) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CycleOutput) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CycleOutput) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CycleOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CycleOutput) GetErrorStage() string {
	if x != nil {
		return x.ErrorStage
	}
	return ""
}

func (x *CycleOutput) GetProcessorOutputJson() []byte {
	if x != nil {
		return x.ProcessorOutputJson
	}
	return nil
}

func (x *CycleOutput) GetGuardResultJson() []byte {
	if x != nil {
		return x.GuardResultJson
	}
	return nil
}

func (x *CycleOutput) GetExecutionResultJson() []byte {
	if x != nil {
		return x.ExecutionResultJson
	}
	return nil
}

type RunCycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*CycleOutput         `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCycleResponse) Reset() {
	*x = RunCycleResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCycleResponse) ProtoMessage() {}

func (x *RunCycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCycleResponse.ProtoReflect.Descriptor instead.
func (*RunCycleResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RunCycleResponse) GetOutputs() []*CycleOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type SetActiveSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveSymbolsRequest) Reset() {
	*x = SetActiveSymbolsRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveSymbolsRequest) ProtoMessage() {}

func (x *SetActiveSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveSymbolsRequest.ProtoReflect.Descriptor instead.
func (*SetActiveSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SetActiveSymbolsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type SetActiveSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActiveSymbols []string               `protobuf:"bytes,2,rep,name=active_symbols,json=activeSymbols,proto3" json:"active_symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveSymbolsResponse) Reset() {
	*x = SetActiveSymbolsResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveSymbolsResponse) ProtoMessage() {}

func (x *SetActiveSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveSymbolsResponse.ProtoReflect.Descriptor instead.
func (*SetActiveSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SetActiveSymbolsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetActiveSymbolsResponse) GetActiveSymbols() []string {
	if x != nil {
		return x.ActiveSymbols
	}
	return nil
}

type GetActiveSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSymbolsRequest) Reset() {
	*x = GetActiveSymbolsRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSymbolsRequest) ProtoMessage() {}

func (x *GetActiveSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSymbolsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

type GetActiveSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // "redis" or "gateway_config"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSymbolsResponse) Reset() {
	*x = GetActiveSymbolsResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSymbolsResponse) ProtoMessage() {}

func (x *GetActiveSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSymbolsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveSymbolsResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *GetActiveSymbolsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ResetActiveSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetActiveSymbolsRequest) Reset() {
	*x = ResetActiveSymbolsRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetActiveSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetActiveSymbolsRequest) ProtoMessage() {}

func (x *ResetActiveSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetActiveSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ResetActiveSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

type ResetActiveSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActiveSymbols []string               `protobuf:"bytes,2,rep,name=active_symbols,json=activeSymbols,proto3" json:"active_symbols,omitempty"` // The default symbols now active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetActiveSymbolsResponse) Reset() {
	*x = ResetActiveSymbolsResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetActiveSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetActiveSymbolsResponse) ProtoMessage() {}

func (x *ResetActiveSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetActiveSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ResetActiveSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ResetActiveSymbolsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetActiveSymbolsResponse) GetActiveSymbols() []string {
	if x != nil {
		return x.ActiveSymbols
	}
	return nil
}

type SetCycleIntervalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New interval in seconds. Must be >= 60 and <= 86400 (24 hours).
	IntervalSeconds int32 `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetCycleIntervalRequest) Reset() {
	*x = SetCycleIntervalRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleIntervalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleIntervalRequest) ProtoMessage() {}

func (x *SetCycleIntervalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleIntervalRequest.ProtoReflect.Descriptor instead.
func (*SetCycleIntervalRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *SetCycleIntervalRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type SetCycleIntervalResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Success                bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CurrentIntervalSeconds int32                  `protobuf:"varint,2,opt,name=current_interval_seconds,json=currentIntervalSeconds,proto3" json:"current_interval_seconds,omitempty"`
	Message                string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetCycleIntervalResponse) Reset() {
	*x = SetCycleIntervalResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleIntervalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleIntervalResponse) ProtoMessage() {}

func (x *SetCycleIntervalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleIntervalResponse.ProtoReflect.Descriptor instead.
func (*SetCycleIntervalResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *SetCycleIntervalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCycleIntervalResponse) GetCurrentIntervalSeconds() int32 {
	if x != nil {
		return x.CurrentIntervalSeconds
	}
	return 0
}

func (x *SetCycleIntervalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGatewayConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayConfigRequest) Reset() {
	*x = GetGatewayConfigRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigRequest) ProtoMessage() {}

func (x *GetGatewayConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

type GetGatewayConfigResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Enabled              bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CycleIntervalSeconds int32                  `protobuf:"varint,2,opt,name=cycle_interval_seconds,json=cycleIntervalSeconds,proto3" json:"cycle_interval_seconds,omitempty"`
	CycleTimeoutSeconds  int32                  `protobuf:"varint,3,opt,name=cycle_timeout_seconds,json=cycleTimeoutSeconds,proto3" json:"cycle_timeout_seconds,omitempty"`
	MaxConcurrentSymbols int32                  `protobuf:"varint,4,opt,name=max_concurrent_symbols,json=maxConcurrentSymbols,proto3" json:"max_concurrent_symbols,omitempty"`
	TaCacheTtlSeconds    int32                  `protobuf:"varint,5,opt,name=ta_cache_ttl_seconds,json=taCacheTtlSeconds,proto3" json:"ta_cache_ttl_seconds,omitempty"`
	MacroCacheTtlSeconds int32                  `protobuf:"varint,6,opt,name=macro_cache_ttl_seconds,json=macroCacheTtlSeconds,proto3" json:"macro_cache_ttl_seconds,omitempty"`
	MaxCycleRetries      int32                  `protobuf:"varint,7,opt,name=max_cycle_retries,json=maxCycleRetries,proto3" json:"max_cycle_retries,omitempty"`
	DefaultSymbols       []string               `protobuf:"bytes,8,rep,name=default_symbols,json=defaultSymbols,proto3" json:"default_symbols,omitempty"`
	ActiveSymbols        []string               `protobuf:"bytes,9,rep,name=active_symbols,json=activeSymbols,proto3" json:"active_symbols,omitempty"`
	ActiveSymbolsSource  string                 `protobuf:"bytes,10,opt,name=active_symbols_source,json=activeSymbolsSource,proto3" json:"active_symbols_source,omitempty"`
	ExecutionEnabled     bool                   `protobuf:"varint,11,opt,name=execution_enabled,json=executionEnabled,proto3" json:"execution_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetGatewayConfigResponse) Reset() {
	*x = GetGatewayConfigResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigResponse) ProtoMessage() {}

func (x *GetGatewayConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *GetGatewayConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetGatewayConfigResponse) GetCycleIntervalSeconds() int32 {
	if x != nil {
		return x.CycleIntervalSeconds
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetCycleTimeoutSeconds() int32 {
	if x != nil {
		return x.CycleTimeoutSeconds
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetMaxConcurrentSymbols() int32 {
	if x != nil {
		return x.MaxConcurrentSymbols
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetTaCacheTtlSeconds() int32 {
	if x != nil {
		return x.TaCacheTtlSeconds
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetMacroCacheTtlSeconds() int32 {
	if x != nil {
		return x.MacroCacheTtlSeconds
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetMaxCycleRetries() int32 {
	if x != nil {
		return x.MaxCycleRetries
	}
	return 0
}

func (x *GetGatewayConfigResponse) GetDefaultSymbols() []string {
	if x != nil {
		return x.DefaultSymbols
	}
	return nil
}

func (x *GetGatewayConfigResponse) GetActiveSymbols() []string {
	if x != nil {
		return x.ActiveSymbols
	}
	return nil
}

func (x *GetGatewayConfigResponse) GetActiveSymbolsSource() string {
	if x != nil {
		return x.ActiveSymbolsSource
	}
	return ""
}

func (x *GetGatewayConfigResponse) GetExecutionEnabled() bool {
	if x != nil {
		return x.ExecutionEnabled
	}
	return false
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

type GetHealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" | "degraded"
	RedisConnected  bool                   `protobuf:"varint,2,opt,name=redis_connected,json=redisConnected,proto3" json:"redis_connected,omitempty"`
	EngineConnected bool                   `protobuf:"varint,3,opt,name=engine_connected,json=engineConnected,proto3" json:"engine_connected,omitempty"`
	ActiveCycles    int32                  `protobuf:"varint,4,opt,name=active_cycles,json=activeCycles,proto3" json:"active_cycles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetRedisConnected() bool {
	if x != nil {
		return x.RedisConnected
	}
	return false
}

func (x *GetHealthResponse) GetEngineConnected() bool {
	if x != nil {
		return x.EngineConnected
	}
	return false
}

func (x *GetHealthResponse) GetActiveCycles() int32 {
	if x != nil {
		return x.ActiveCycles
	}
	return 0
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"F\n" +
	"\x0fRunCycleRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\x99\x03\n" +
	"\vCycleOutput\x12!\n" +
	"\fcycle_status\x18\x01 \x01(\tR\vcycleStatus\x12#\n" +
	"\rcycle_outcome\x18\x02 \x01(\tR\fcycleOutcome\x12#\n" +
	"\rphase_reached\x18\x03 \x01(\tR\fphaseReached\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x01R\n" +
	"durationMs\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1f\n" +
	"\verror_stage\x18\b \x01(\tR\n" +
	"errorStage\x122\n" +
	"\x15processor_output_json\x18\t \x01(\fR\x13processorOutputJson\x12*\n" +
	"\x11guard_result_json\x18\n" +
	" \x01(\fR\x0fguardResultJson\x122\n" +
	"\x15execution_result_json\x18\v \x01(\fR\x13executionResultJson\"E\n" +
	"\x10RunCycleResponse\x121\n" +
	"\aoutputs\x18\x01 \x03(\v2\x17.gateway.v1.CycleOutputR\aoutputs\"3\n" +
	"\x17SetActiveSymbolsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"[\n" +
	"\x18SetActiveSymbolsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eactive_symbols\x18\x02 \x03(\tR\ractiveSymbols\"\x19\n" +
	"\x17GetActiveSymbolsRequest\"L\n" +
	"\x18GetActiveSymbolsResponse\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\x1b\n" +
	"\x19ResetActiveSymbolsRequest\"]\n" +
	"\x1aResetActiveSymbolsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eactive_symbols\x18\x02 \x03(\tR\ractiveSymbols\"D\n" +
	"\x17SetCycleIntervalRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\"\x88\x01\n" +
	"\x18SetCycleIntervalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x18current_interval_seconds\x18\x02 \x01(\x05R\x16currentIntervalSeconds\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x19\n" +
	"\x17GetGatewayConfigRequest\"\x99\x04\n" +
	"\x18GetGatewayConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x124\n" +
	"\x16cycle_interval_seconds\x18\x02 \x01(\x05R\x14cycleIntervalSeconds\x122\n" +
	"\x15cycle_timeout_seconds\x18\x03 \x01(\x05R\x13cycleTimeoutSeconds\x124\n" +
	"\x16max_concurrent_symbols\x18\x04 \x01(\x05R\x14maxConcurrentSymbols\x12/\n" +
	"\x14ta_cache_ttl_seconds\x18\x05 \x01(\x05R\x11taCacheTtlSeconds\x125\n" +
	"\x17macro_cache_ttl_seconds\x18\x06 \x01(\x05R\x14macroCacheTtlSeconds\x12*\n" +
	"\x11max_cycle_retries\x18\a \x01(\x05R\x0fmaxCycleRetries\x12'\n" +
	"\x0fdefault_symbols\x18\b \x03(\tR\x0edefaultSymbols\x12%\n" +
	"\x0eactive_symbols\x18\t \x03(\tR\ractiveSymbols\x122\n" +
	"\x15active_symbols_source\x18\n" +
	" \x01(\tR\x13activeSymbolsSource\x12+\n" +
	"\x11execution_enabled\x18\v \x01(\bR\x10executionEnabled\"\x12\n" +
	"\x10GetHealthRequest\"\xa4\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0fredis_connected\x18\x02 \x01(\bR\x0eredisConnected\x12)\n" +
	"\x10engine_connected\x18\x03 \x01(\bR\x0fengineConnected\x12#\n" +
	"\ractive_cycles\x18\x04 \x01(\x05R\factiveCycles2\x82\x05\n" +
	"\x0eGatewayService\x12E\n" +
	"\bRunCycle\x12\x1b.gateway.v1.RunCycleRequest\x1a\x1c.gateway.v1.RunCycleResponse\x12]\n" +
	"\x10SetActiveSymbols\x12#.gateway.v1.SetActiveSymbolsRequest\x1a$.gateway.v1.SetActiveSymbolsResponse\x12]\n" +
	"\x10GetActiveSymbols\x12#.gateway.v1.GetActiveSymbolsRequest\x1a$.gateway.v1.GetActiveSymbolsResponse\x12c\n" +
	"\x12ResetActiveSymbols\x12%.gateway.v1.ResetActiveSymbolsRequest\x1a&.gateway.v1.ResetActiveSymbolsResponse\x12]\n" +
	"\x10SetCycleInterval\x12#.gateway.v1.SetCycleIntervalRequest\x1a$.gateway.v1.SetCycleIntervalResponse\x12]\n" +
	"\x10GetGatewayConfig\x12#.gateway.v1.GetGatewayConfigRequest\x1a$.gateway.v1.GetGatewayConfigResponse\x12H\n" +
	"\tGetHealth\x12\x1c.gateway.v1.GetHealthRequest\x1a\x1d.gateway.v1.GetHealthResponseB:Z8github.com/flamegreat/etradie/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*RunCycleRequest)(nil),            // 0: gateway.v1.RunCycleRequest
	(*CycleOutput)(nil),                // 1: gateway.v1.CycleOutput
	(*RunCycleResponse)(nil),           // 2: gateway.v1.RunCycleResponse
	(*SetActiveSymbolsRequest)(nil),    // 3: gateway.v1.SetActiveSymbolsRequest
	(*SetActiveSymbolsResponse)(nil),   // 4: gateway.v1.SetActiveSymbolsResponse
	(*GetActiveSymbolsRequest)(nil),    // 5: gateway.v1.GetActiveSymbolsRequest
	(*GetActiveSymbolsResponse)(nil),   // 6: gateway.v1.GetActiveSymbolsResponse
	(*ResetActiveSymbolsRequest)(nil),  // 7: gateway.v1.ResetActiveSymbolsRequest
	(*ResetActiveSymbolsResponse)(nil), // 8: gateway.v1.ResetActiveSymbolsResponse
	(*SetCycleIntervalRequest)(nil),    // 9: gateway.v1.SetCycleIntervalRequest
	(*SetCycleIntervalResponse)(nil),   // 10: gateway.v1.SetCycleIntervalResponse
	(*GetGatewayConfigRequest)(nil),    // 11: gateway.v1.GetGatewayConfigRequest
	(*GetGatewayConfigResponse)(nil),   // 12: gateway.v1.GetGatewayConfigResponse
	(*GetHealthRequest)(nil),           // 13: gateway.v1.GetHealthRequest
	(*GetHealthResponse)(nil),          // 14: gateway.v1.GetHealthResponse
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	1,  // 0: gateway.v1.RunCycleResponse.outputs:type_name -> gateway.v1.CycleOutput
	0,  // 1: gateway.v1.GatewayService.RunCycle:input_type -> gateway.v1.RunCycleRequest
	3,  // 2: gateway.v1.GatewayService.SetActiveSymbols:input_type -> gateway.v1.SetActiveSymbolsRequest
	5,  // 3: gateway.v1.GatewayService.GetActiveSymbols:input_type -> gateway.v1.GetActiveSymbolsRequest
	7,  // 4: gateway.v1.GatewayService.ResetActiveSymbols:input_type -> gateway.v1.ResetActiveSymbolsRequest
	9,  // 5: gateway.v1.GatewayService.SetCycleInterval:input_type -> gateway.v1.SetCycleIntervalRequest
	11, // 6: gateway.v1.GatewayService.GetGatewayConfig:input_type -> gateway.v1.GetGatewayConfigRequest
	13, // 7: gateway.v1.GatewayService.GetHealth:input_type -> gateway.v1.GetHealthRequest
	2,  // 8: gateway.v1.GatewayService.RunCycle:output_type -> gateway.v1.RunCycleResponse
	4,  // 9: gateway.v1.GatewayService.SetActiveSymbols:output_type -> gateway.v1.SetActiveSymbolsResponse
	6,  // 10: gateway.v1.GatewayService.GetActiveSymbols:output_type -> gateway.v1.GetActiveSymbolsResponse
	8,  // 11: gateway.v1.GatewayService.ResetActiveSymbols:output_type -> gateway.v1.ResetActiveSymbolsResponse
	10, // 12: gateway.v1.GatewayService.SetCycleInterval:output_type -> gateway.v1.SetCycleIntervalResponse
	12, // 13: gateway.v1.GatewayService.GetGatewayConfig:output_type -> gateway.v1.GetGatewayConfigResponse
	14, // 14: gateway.v1.GatewayService.GetHealth:output_type -> gateway.v1.GetHealthResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
