import {
  AlertOctagon,
  Brain,
  ClipboardList,
  Compass,
  FileText,
  Gauge,
  GitCompareArrows,
  Heart,
  LineChart,
  ListChecks,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
} from 'lucide-react';
import type { PerformanceReview } from '../types';
import {
  ConfidenceBadge,
  DirectionBadge,
  EmptyState,
  MetricTile,
  PnLDirectionIcon,
  ReviewCard,
  SeverityBadge,
} from './primitives';

/**
 * Renders the full 14-section review.
 *
 * Layout strategy:
 *   - Executive Summary spans the full width at the top so it reads
 *     like the cover paragraph of an institutional report.
 *   - Performance Metrics renders as an 8-tile grid that collapses
 *     gracefully from 4 columns on desktop to 2 on tablet to 1 on
 *     mobile.
 *   - The remaining sections render as a 2-column grid on lg+
 *     and stack on smaller screens. Long-form sections (Behavioral,
 *     Improvement Recs) keep their natural ordering so the read flow
 *     mirrors the PLAN.md section sequence.
 */
export function PerformanceReviewSections({ review }: { review: PerformanceReview }) {
  const lowSample =
    review.confidence_report.band === 'low' || review.confidence_report.band === 'insufficient';

  return (
    <div className="flex flex-col gap-4 sm:gap-5">
      {/* Section 1: Executive Summary - cover paragraph, full width */}
      <ReviewCard
        title="Executive Summary"
        subtitle={`Generated by ${review.generated_by || 'Exoper AI'}`}
        icon={<FileText size={16} aria-hidden />}
        action={
          <ConfidenceBadge
            band={review.confidence_report.band}
            sampleSize={review.confidence_report.sample_size}
          />
        }
      >
        {review.executive_summary.headline && (
          <p className="text-sm sm:text-base font-bold text-black dark:text-white">
            {review.executive_summary.headline}
          </p>
        )}
        {review.executive_summary.narrative ? (
          <p className="mt-2 text-xs sm:text-sm leading-relaxed text-black/70 dark:text-white/70 whitespace-pre-wrap">
            {review.executive_summary.narrative}
          </p>
        ) : (
          <EmptyState message="No narrative available." />
        )}
      </ReviewCard>

      {/* Section 2: Performance Metrics - full-width tile grid */}
      <ReviewCard
        title="Performance Metrics"
        subtitle="Deterministic aggregates over the window"
        icon={<LineChart size={16} aria-hidden />}
      >
        <div className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 sm:gap-3">
          <MetricTile label="Total Trades" value={review.performance_metrics.total_trades} />
          <MetricTile label="Win Rate" value={review.performance_metrics.win_rate} />
          <MetricTile label="Avg RR" value={review.performance_metrics.avg_rr} />
          <div className="flex flex-col gap-1 rounded-xl border border-black/5 dark:border-white/5 p-3 sm:p-4 bg-black/[0.02] dark:bg-white/[0.02]">
            <span className="text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-black/40 dark:text-white/40">
              Net P&L
            </span>
            <span className="text-base sm:text-lg font-bold tracking-tight inline-flex items-center gap-1.5 text-black dark:text-white">
              <PnLDirectionIcon value={review.performance_metrics.net_pnl} />
              {review.performance_metrics.net_pnl?.trim() || '\u2014'}
            </span>
          </div>
          <MetricTile label="Best Session" value={review.performance_metrics.best_session} />
          <MetricTile label="Worst Session" value={review.performance_metrics.worst_session} />
          <MetricTile
            label="Most Profitable Setup"
            value={review.performance_metrics.most_profitable_setup}
          />
          <MetricTile label="Worst Behavior" value={review.performance_metrics.worst_behavior} />
        </div>
      </ReviewCard>

      {/* Two-column layout for sections 3-14 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-5">
        {/* Section 3: Behavioral Analysis */}
        <ReviewCard title="Behavioral Analysis" icon={<Brain size={16} aria-hidden />}>
          {review.behavioral_analysis.patterns.length > 0 ? (
            <ul className="flex flex-col gap-2.5">
              {review.behavioral_analysis.patterns.map((p, i) => (
                <li key={i} className="flex items-start gap-2.5 text-xs sm:text-sm text-black/80 dark:text-white/80">
                  <Sparkles
                    size={14}
                    className="text-black/30 dark:text-white/30 shrink-0 mt-0.5"
                    aria-hidden
                  />
                  <span className="min-w-0">{p}</span>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState
              message="No behavioral patterns surfaced."
              hint={lowSample ? 'Sample too small for analysis.' : undefined}
            />
          )}
        </ReviewCard>

        {/* Section 4: System Adherence */}
        <ReviewCard title="System Adherence" icon={<ShieldCheck size={16} aria-hidden />}>
          {review.system_adherence.items.length > 0 ? (
            <div className="overflow-x-auto -mx-1">
              <table className="min-w-full text-xs sm:text-sm">
                <thead>
                  <tr className="text-left text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-black/40 dark:text-white/40">
                    <th className="py-2 px-1 font-bold">Rule</th>
                    <th className="py-2 px-1 font-bold text-right">Compliance</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-black/5 dark:divide-white/5">
                  {review.system_adherence.items.map((it, i) => (
                    <tr key={i}>
                      <td className="py-2 px-1 text-black/80 dark:text-white/80">{it.rule}</td>
                      <td className="py-2 px-1 text-right font-bold text-black dark:text-white">
                        {it.compliance || '\u2014'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState message="No adherence rows scored." />
          )}
        </ReviewCard>

        {/* Section 5: Emotional Intelligence */}
        <ReviewCard title="Emotional Intelligence" icon={<Heart size={16} aria-hidden />}>
          {review.emotional_intelligence.narrative ? (
            <p className="text-xs sm:text-sm leading-relaxed text-black/70 dark:text-white/70 whitespace-pre-wrap">
              {review.emotional_intelligence.narrative}
            </p>
          ) : (
            <EmptyState
              message="No emotional pattern surfaced."
              hint={lowSample ? 'Sample too small for analysis.' : undefined}
            />
          )}
        </ReviewCard>

        {/* Section 6: Setup Quality */}
        <ReviewCard title="Setup Quality" icon={<Target size={16} aria-hidden />}>
          {review.setup_quality.items.length > 0 ? (
            <div className="overflow-x-auto -mx-1">
              <table className="min-w-full text-xs sm:text-sm">
                <thead>
                  <tr className="text-left text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-black/40 dark:text-white/40">
                    <th className="py-2 px-1">Setup</th>
                    <th className="py-2 px-1 text-right">Win Rate</th>
                    <th className="py-2 px-1 text-right">Avg RR</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-black/5 dark:divide-white/5">
                  {review.setup_quality.items.map((it, i) => (
                    <tr key={i}>
                      <td className="py-2 px-1 text-black/80 dark:text-white/80">{it.setup}</td>
                      <td className="py-2 px-1 text-right font-bold text-black dark:text-white">
                        {it.win_rate || '\u2014'}
                      </td>
                      <td className="py-2 px-1 text-right text-black/70 dark:text-white/70">
                        {it.avg_rr || '\u2014'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState message="No setups graded." />
          )}
        </ReviewCard>

        {/* Section 7: Session Analysis */}
        <ReviewCard title="Session Analysis" icon={<Compass size={16} aria-hidden />}>
          {review.session_analysis.items.length > 0 ? (
            <div className="overflow-x-auto -mx-1">
              <table className="min-w-full text-xs sm:text-sm">
                <thead>
                  <tr className="text-left text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-black/40 dark:text-white/40">
                    <th className="py-2 px-1">Session</th>
                    <th className="py-2 px-1">Performance</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-black/5 dark:divide-white/5">
                  {review.session_analysis.items.map((it, i) => (
                    <tr key={i}>
                      <td className="py-2 px-1 text-black/80 dark:text-white/80">{it.session}</td>
                      <td className="py-2 px-1 text-black/70 dark:text-white/70">
                        {it.performance || '\u2014'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState message="No session data." />
          )}
        </ReviewCard>

        {/* Section 8: Risk Analysis */}
        <ReviewCard title="Risk Analysis" icon={<Gauge size={16} aria-hidden />}>
          {review.risk_analysis.narrative ? (
            <p className="text-xs sm:text-sm leading-relaxed text-black/70 dark:text-white/70 whitespace-pre-wrap">
              {review.risk_analysis.narrative}
            </p>
          ) : (
            <EmptyState message="No risk analysis." />
          )}
        </ReviewCard>

        {/* Section 9: Improvement Recommendations */}
        <ReviewCard title="Improvement Recommendations" icon={<ClipboardList size={16} aria-hidden />}>
          {review.improvement_recommendations.items.length > 0 ? (
            <ol className="flex flex-col gap-2.5 list-none">
              {review.improvement_recommendations.items.map((p, i) => (
                <li key={i} className="flex items-start gap-3 text-xs sm:text-sm text-black/80 dark:text-white/80">
                  <span className="shrink-0 w-5 h-5 rounded-md bg-black/5 dark:bg-white/5 flex items-center justify-center text-[10px] font-bold text-black/60 dark:text-white/60">
                    {i + 1}
                  </span>
                  <span className="min-w-0">{p}</span>
                </li>
              ))}
            </ol>
          ) : (
            <EmptyState
              message="No recommendations."
              hint={lowSample ? 'Build more sample size first.' : undefined}
            />
          )}
        </ReviewCard>

        {/* Section 10: Next Period Focus */}
        <ReviewCard title="Next Period Focus" icon={<ListChecks size={16} aria-hidden />}>
          {review.next_focus.items.length > 0 ? (
            <ul className="flex flex-col gap-2.5">
              {review.next_focus.items.map((p, i) => (
                <li key={i} className="flex items-start gap-2.5 text-xs sm:text-sm text-black/80 dark:text-white/80">
                  <span
                    aria-hidden
                    className="shrink-0 mt-1 w-1.5 h-1.5 rounded-full bg-black/40 dark:bg-white/40"
                  />
                  <span className="min-w-0">{p}</span>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState message="No focus areas." />
          )}
        </ReviewCard>

        {/* Section 11: Confidence & Data Quality */}
        <ReviewCard
          title="Confidence & Data Quality"
          icon={<Sparkles size={16} aria-hidden />}
          action={
            <ConfidenceBadge
              band={review.confidence_report.band}
              sampleSize={review.confidence_report.sample_size}
            />
          }
        >
          <p className="text-xs sm:text-sm leading-relaxed text-black/70 dark:text-white/70">
            {review.confidence_report.note ||
              'Confidence is derived from the deterministic sample size; the LLM is bound by this band.'}
          </p>
        </ReviewCard>

        {/* Section 12: Trader Evolution */}
        <ReviewCard title="Trader Evolution" icon={<TrendingUp size={16} aria-hidden />}>
          {review.trader_evolution.items.length > 0 ? (
            <ul className="flex flex-col divide-y divide-black/5 dark:divide-white/5">
              {review.trader_evolution.items.map((it, i) => (
                <li key={i} className="flex items-center justify-between gap-3 py-2.5">
                  <span className="text-xs sm:text-sm font-medium text-black/80 dark:text-white/80 truncate">
                    {it.metric}
                  </span>
                  <DirectionBadge direction={it.direction} delta={it.delta} />
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState
              message="No prior review to compare against."
              hint="Evolution deltas appear from the second review onward."
            />
          )}
        </ReviewCard>

        {/* Section 13: System Alignment (spans full width on lg+ for emphasis) */}
        <ReviewCard
          title="Performance vs Trading System"
          subtitle="Defined framework compared against observed behavior"
          icon={<GitCompareArrows size={16} aria-hidden />}
          className="lg:col-span-2"
        >
          {review.system_alignment.narrative ? (
            <p className="text-xs sm:text-sm leading-relaxed text-black/70 dark:text-white/70 whitespace-pre-wrap">
              {review.system_alignment.narrative}
            </p>
          ) : (
            <EmptyState message="No alignment analysis." />
          )}
          {review.system_alignment.gaps.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-2">
              {review.system_alignment.gaps.map((g, i) => (
                <span
                  key={i}
                  className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] sm:text-[11px] font-bold border border-amber-500/20 bg-amber-500/10 text-amber-700 dark:text-amber-300"
                >
                  {g}
                </span>
              ))}
            </div>
          )}
        </ReviewCard>

        {/* Section 14: Psychological Warnings (spans full width on lg+) */}
        <ReviewCard
          title="AI Psychological Warnings"
          icon={<AlertOctagon size={16} aria-hidden />}
          className="lg:col-span-2"
        >
          {review.psychological_warnings.items.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {review.psychological_warnings.items.map((it, i) => (
                <article
                  key={i}
                  className="rounded-xl border border-black/5 dark:border-white/5 bg-black/[0.02] dark:bg-white/[0.02] p-3 sm:p-4 flex flex-col gap-1.5"
                >
                  <div className="flex items-center justify-between gap-2">
                    <h4 className="text-xs sm:text-sm font-bold text-black dark:text-white truncate">
                      {it.signal}
                    </h4>
                    <SeverityBadge severity={it.severity} />
                  </div>
                  <p className="text-[11px] sm:text-xs text-black/60 dark:text-white/60 leading-relaxed">
                    {it.explanation}
                  </p>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState
              message="No psychological warnings."
              hint="This is a positive signal: no risk patterns flagged this period."
            />
          )}
        </ReviewCard>
      </div>
    </div>
  );
}
