{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "billing.appName" . }}
  namespace: {{ include "billing.namespace" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
    app.kubernetes.io/component: availability
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "billing.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy | default "IfHealthyBudget" }}
{{- end }}
