// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: execution/v1/execution.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteTradeRequest carries everything Module B needs from the gateway.
// Maps 1:1 from ProcessorOutput fields. No macro reasoning, no RAG
// citations, no evidence chains. Pure execution data.
type ExecuteTradeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction       string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "LONG" or "SHORT"
	EntryZoneLow    float64                `protobuf:"fixed64,3,opt,name=entry_zone_low,json=entryZoneLow,proto3" json:"entry_zone_low,omitempty"`
	EntryZoneHigh   float64                `protobuf:"fixed64,4,opt,name=entry_zone_high,json=entryZoneHigh,proto3" json:"entry_zone_high,omitempty"`
	StopLoss        float64                `protobuf:"fixed64,5,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	Tp1Price        float64                `protobuf:"fixed64,6,opt,name=tp1_price,json=tp1Price,proto3" json:"tp1_price,omitempty"`
	Tp1Pct          int32                  `protobuf:"varint,7,opt,name=tp1_pct,json=tp1Pct,proto3" json:"tp1_pct,omitempty"` // e.g. 40
	Tp2Price        float64                `protobuf:"fixed64,8,opt,name=tp2_price,json=tp2Price,proto3" json:"tp2_price,omitempty"`
	Tp2Pct          int32                  `protobuf:"varint,9,opt,name=tp2_pct,json=tp2Pct,proto3" json:"tp2_pct,omitempty"` // e.g. 30
	Tp3Price        float64                `protobuf:"fixed64,10,opt,name=tp3_price,json=tp3Price,proto3" json:"tp3_price,omitempty"`
	Tp3Pct          int32                  `protobuf:"varint,11,opt,name=tp3_pct,json=tp3Pct,proto3" json:"tp3_pct,omitempty"` // e.g. 30
	RrRatio         float64                `protobuf:"fixed64,12,opt,name=rr_ratio,json=rrRatio,proto3" json:"rr_ratio,omitempty"`
	Grade           string                 `protobuf:"bytes,13,opt,name=grade,proto3" json:"grade,omitempty"`                                           // "A+", "A", "B"
	RiskPercentage  float64                `protobuf:"fixed64,14,opt,name=risk_percentage,json=riskPercentage,proto3" json:"risk_percentage,omitempty"` // 1.0 or 0.5
	TradingStyle    string                 `protobuf:"bytes,15,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"`         // "SCALPING", "INTRADAY", "SWING", "POSITIONAL"
	Session         string                 `protobuf:"bytes,16,opt,name=session,proto3" json:"session,omitempty"`                                       // "LONDON_OPEN", "LONDON_NY_OVERLAP", etc.
	ConfluenceScore float64                `protobuf:"fixed64,17,opt,name=confluence_score,json=confluenceScore,proto3" json:"confluence_score,omitempty"`
	Confidence      float64                `protobuf:"fixed64,18,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AnalysisId      string                 `protobuf:"bytes,19,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"` // Links back to Module A output
	TraceId         string                 `protobuf:"bytes,20,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteTradeRequest) Reset() {
	*x = ExecuteTradeRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTradeRequest) ProtoMessage() {}

func (x *ExecuteTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTradeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTradeRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteTradeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExecuteTradeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ExecuteTradeRequest) GetEntryZoneLow() float64 {
	if x != nil {
		return x.EntryZoneLow
	}
	return 0
}

func (x *ExecuteTradeRequest) GetEntryZoneHigh() float64 {
	if x != nil {
		return x.EntryZoneHigh
	}
	return 0
}

func (x *ExecuteTradeRequest) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp1Price() float64 {
	if x != nil {
		return x.Tp1Price
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp1Pct() int32 {
	if x != nil {
		return x.Tp1Pct
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp2Price() float64 {
	if x != nil {
		return x.Tp2Price
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp2Pct() int32 {
	if x != nil {
		return x.Tp2Pct
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp3Price() float64 {
	if x != nil {
		return x.Tp3Price
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTp3Pct() int32 {
	if x != nil {
		return x.Tp3Pct
	}
	return 0
}

func (x *ExecuteTradeRequest) GetRrRatio() float64 {
	if x != nil {
		return x.RrRatio
	}
	return 0
}

func (x *ExecuteTradeRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *ExecuteTradeRequest) GetRiskPercentage() float64 {
	if x != nil {
		return x.RiskPercentage
	}
	return 0
}

func (x *ExecuteTradeRequest) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

func (x *ExecuteTradeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ExecuteTradeRequest) GetConfluenceScore() float64 {
	if x != nil {
		return x.ConfluenceScore
	}
	return 0
}

func (x *ExecuteTradeRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExecuteTradeRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *ExecuteTradeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ExecuteTradeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                     // true if order was placed or watcher armed
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                          // "LIMIT_ORDER_PLACED", "WATCHER_ARMED", "REJECTED", "QUEUED", "LOCKED", "PAUSED"
	OrderId         string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                         // Broker order ID (limit) or watcher ID (instant)
	RejectionReason string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // Which check failed, empty if accepted
	RejectionCheck  int32                  `protobuf:"varint,5,opt,name=rejection_check,json=rejectionCheck,proto3" json:"rejection_check,omitempty"`   // Check number (4-13) that failed, 0 if accepted
	// Sizing breakdown (populated when accepted).
	LotSize        float64 `protobuf:"fixed64,6,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	RiskAmount     float64 `protobuf:"fixed64,7,opt,name=risk_amount,json=riskAmount,proto3" json:"risk_amount,omitempty"`             // Dollar amount risked
	AccountBalance float64 `protobuf:"fixed64,8,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"` // Balance at time of calculation
	SlDistancePips float64 `protobuf:"fixed64,9,opt,name=sl_distance_pips,json=slDistancePips,proto3" json:"sl_distance_pips,omitempty"`
	PipValue       float64 `protobuf:"fixed64,10,opt,name=pip_value,json=pipValue,proto3" json:"pip_value,omitempty"`
	// Order details (populated when accepted).
	ExecutionMode string  `protobuf:"bytes,11,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"` // "LIMIT" or "INSTANT"
	EntryPrice    float64 `protobuf:"fixed64,12,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`        // Actual entry price used (midpoint or OTE)
	AnalysisId    string  `protobuf:"bytes,13,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	TraceId       string  `protobuf:"bytes,14,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTradeResponse) Reset() {
	*x = ExecuteTradeResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTradeResponse) ProtoMessage() {}

func (x *ExecuteTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTradeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTradeResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTradeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ExecuteTradeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteTradeResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecuteTradeResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *ExecuteTradeResponse) GetRejectionCheck() int32 {
	if x != nil {
		return x.RejectionCheck
	}
	return 0
}

func (x *ExecuteTradeResponse) GetLotSize() float64 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *ExecuteTradeResponse) GetRiskAmount() float64 {
	if x != nil {
		return x.RiskAmount
	}
	return 0
}

func (x *ExecuteTradeResponse) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

func (x *ExecuteTradeResponse) GetSlDistancePips() float64 {
	if x != nil {
		return x.SlDistancePips
	}
	return 0
}

func (x *ExecuteTradeResponse) GetPipValue() float64 {
	if x != nil {
		return x.PipValue
	}
	return 0
}

func (x *ExecuteTradeResponse) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *ExecuteTradeResponse) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *ExecuteTradeResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *ExecuteTradeResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Broker order ID or watcher ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // "STRUCTURE_BREAK", "THESIS_CHANGED", "MANUAL", "TTL_EXPIRED"
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelOrderRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "CANCELLED", "NOT_FOUND", "ALREADY_FILLED"
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelOrderResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetStateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpenPositionCount int32                  `protobuf:"varint,1,opt,name=open_position_count,json=openPositionCount,proto3" json:"open_position_count,omitempty"`
	PendingOrderCount int32                  `protobuf:"varint,2,opt,name=pending_order_count,json=pendingOrderCount,proto3" json:"pending_order_count,omitempty"`
	DailyRealizedPnl  float64                `protobuf:"fixed64,3,opt,name=daily_realized_pnl,json=dailyRealizedPnl,proto3" json:"daily_realized_pnl,omitempty"`
	WeeklyRealizedPnl float64                `protobuf:"fixed64,4,opt,name=weekly_realized_pnl,json=weeklyRealizedPnl,proto3" json:"weekly_realized_pnl,omitempty"`
	AccountBalance    float64                `protobuf:"fixed64,5,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	AccountEquity     float64                `protobuf:"fixed64,6,opt,name=account_equity,json=accountEquity,proto3" json:"account_equity,omitempty"`
	OpenPositions     []*OpenPosition        `protobuf:"bytes,7,rep,name=open_positions,json=openPositions,proto3" json:"open_positions,omitempty"`
	PendingOrders     []*PendingOrder        `protobuf:"bytes,8,rep,name=pending_orders,json=pendingOrders,proto3" json:"pending_orders,omitempty"`
	TraceId           string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *GetStateResponse) GetOpenPositionCount() int32 {
	if x != nil {
		return x.OpenPositionCount
	}
	return 0
}

func (x *GetStateResponse) GetPendingOrderCount() int32 {
	if x != nil {
		return x.PendingOrderCount
	}
	return 0
}

func (x *GetStateResponse) GetDailyRealizedPnl() float64 {
	if x != nil {
		return x.DailyRealizedPnl
	}
	return 0
}

func (x *GetStateResponse) GetWeeklyRealizedPnl() float64 {
	if x != nil {
		return x.WeeklyRealizedPnl
	}
	return 0
}

func (x *GetStateResponse) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

func (x *GetStateResponse) GetAccountEquity() float64 {
	if x != nil {
		return x.AccountEquity
	}
	return 0
}

func (x *GetStateResponse) GetOpenPositions() []*OpenPosition {
	if x != nil {
		return x.OpenPositions
	}
	return nil
}

func (x *GetStateResponse) GetPendingOrders() []*PendingOrder {
	if x != nil {
		return x.PendingOrders
	}
	return nil
}

func (x *GetStateResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type OpenPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,5,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	LotSize       float64                `protobuf:"fixed64,6,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,7,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	OrderId       string                 `protobuf:"bytes,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,9,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	TradingStyle  string                 `protobuf:"bytes,10,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPosition) Reset() {
	*x = OpenPosition{}
	mi := &file_execution_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPosition) ProtoMessage() {}

func (x *OpenPosition) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPosition.ProtoReflect.Descriptor instead.
func (*OpenPosition) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *OpenPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OpenPosition) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OpenPosition) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *OpenPosition) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *OpenPosition) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *OpenPosition) GetLotSize() float64 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *OpenPosition) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *OpenPosition) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenPosition) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *OpenPosition) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

type PendingOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,4,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	LotSize       float64                `protobuf:"fixed64,5,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,7,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ExecutionMode string                 `protobuf:"bytes,8,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"` // "LIMIT" or "INSTANT"
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                    // "PENDING", "WATCHING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingOrder) Reset() {
	*x = PendingOrder{}
	mi := &file_execution_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOrder) ProtoMessage() {}

func (x *PendingOrder) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOrder.ProtoReflect.Descriptor instead.
func (*PendingOrder) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *PendingOrder) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PendingOrder) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PendingOrder) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *PendingOrder) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *PendingOrder) GetLotSize() float64 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *PendingOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PendingOrder) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *PendingOrder) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *PendingOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_execution_v1_execution_proto protoreflect.FileDescriptor

const file_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1cexecution/v1/execution.proto\x12\fexecution.v1\"\xf8\x04\n" +
	"\x13ExecuteTradeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12$\n" +
	"\x0eentry_zone_low\x18\x03 \x01(\x01R\fentryZoneLow\x12&\n" +
	"\x0fentry_zone_high\x18\x04 \x01(\x01R\rentryZoneHigh\x12\x1b\n" +
	"\tstop_loss\x18\x05 \x01(\x01R\bstopLoss\x12\x1b\n" +
	"\ttp1_price\x18\x06 \x01(\x01R\btp1Price\x12\x17\n" +
	"\atp1_pct\x18\a \x01(\x05R\x06tp1Pct\x12\x1b\n" +
	"\ttp2_price\x18\b \x01(\x01R\btp2Price\x12\x17\n" +
	"\atp2_pct\x18\t \x01(\x05R\x06tp2Pct\x12\x1b\n" +
	"\ttp3_price\x18\n" +
	" \x01(\x01R\btp3Price\x12\x17\n" +
	"\atp3_pct\x18\v \x01(\x05R\x06tp3Pct\x12\x19\n" +
	"\brr_ratio\x18\f \x01(\x01R\arrRatio\x12\x14\n" +
	"\x05grade\x18\r \x01(\tR\x05grade\x12'\n" +
	"\x0frisk_percentage\x18\x0e \x01(\x01R\x0eriskPercentage\x12#\n" +
	"\rtrading_style\x18\x0f \x01(\tR\ftradingStyle\x12\x18\n" +
	"\asession\x18\x10 \x01(\tR\asession\x12)\n" +
	"\x10confluence_score\x18\x11 \x01(\x01R\x0fconfluenceScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x12 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vanalysis_id\x18\x13 \x01(\tR\n" +
	"analysisId\x12\x19\n" +
	"\btrace_id\x18\x14 \x01(\tR\atraceId\"\xe9\x03\n" +
	"\x14ExecuteTradeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12'\n" +
	"\x0frejection_check\x18\x05 \x01(\x05R\x0erejectionCheck\x12\x19\n" +
	"\blot_size\x18\x06 \x01(\x01R\alotSize\x12\x1f\n" +
	"\vrisk_amount\x18\a \x01(\x01R\n" +
	"riskAmount\x12'\n" +
	"\x0faccount_balance\x18\b \x01(\x01R\x0eaccountBalance\x12(\n" +
	"\x10sl_distance_pips\x18\t \x01(\x01R\x0eslDistancePips\x12\x1b\n" +
	"\tpip_value\x18\n" +
	" \x01(\x01R\bpipValue\x12%\n" +
	"\x0eexecution_mode\x18\v \x01(\tR\rexecutionMode\x12\x1f\n" +
	"\ventry_price\x18\f \x01(\x01R\n" +
	"entryPrice\x12\x1f\n" +
	"\vanalysis_id\x18\r \x01(\tR\n" +
	"analysisId\x12\x19\n" +
	"\btrace_id\x18\x0e \x01(\tR\atraceId\"z\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"b\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\",\n" +
	"\x0fGetStateRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"\xc1\x03\n" +
	"\x10GetStateResponse\x12.\n" +
	"\x13open_position_count\x18\x01 \x01(\x05R\x11openPositionCount\x12.\n" +
	"\x13pending_order_count\x18\x02 \x01(\x05R\x11pendingOrderCount\x12,\n" +
	"\x12daily_realized_pnl\x18\x03 \x01(\x01R\x10dailyRealizedPnl\x12.\n" +
	"\x13weekly_realized_pnl\x18\x04 \x01(\x01R\x11weeklyRealizedPnl\x12'\n" +
	"\x0faccount_balance\x18\x05 \x01(\x01R\x0eaccountBalance\x12%\n" +
	"\x0eaccount_equity\x18\x06 \x01(\x01R\raccountEquity\x12A\n" +
	"\x0eopen_positions\x18\a \x03(\v2\x1a.execution.v1.OpenPositionR\ropenPositions\x12A\n" +
	"\x0epending_orders\x18\b \x03(\v2\x1a.execution.v1.PendingOrderR\rpendingOrders\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"\xca\x02\n" +
	"\fOpenPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x1f\n" +
	"\ventry_price\x18\x03 \x01(\x01R\n" +
	"entryPrice\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x01R\fcurrentPrice\x12\x1b\n" +
	"\tstop_loss\x18\x05 \x01(\x01R\bstopLoss\x12\x19\n" +
	"\blot_size\x18\x06 \x01(\x01R\alotSize\x12%\n" +
	"\x0eunrealized_pnl\x18\a \x01(\x01R\runrealizedPnl\x12\x19\n" +
	"\border_id\x18\b \x01(\tR\aorderId\x12\x1f\n" +
	"\vanalysis_id\x18\t \x01(\tR\n" +
	"analysisId\x12#\n" +
	"\rtrading_style\x18\n" +
	" \x01(\tR\ftradingStyle\"\x98\x02\n" +
	"\fPendingOrder\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x1f\n" +
	"\ventry_price\x18\x03 \x01(\x01R\n" +
	"entryPrice\x12\x1b\n" +
	"\tstop_loss\x18\x04 \x01(\x01R\bstopLoss\x12\x19\n" +
	"\blot_size\x18\x05 \x01(\x01R\alotSize\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12\x1f\n" +
	"\vanalysis_id\x18\a \x01(\tR\n" +
	"analysisId\x12%\n" +
	"\x0eexecution_mode\x18\b \x01(\tR\rexecutionMode\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status2\x98\x02\n" +
	"\x10ExecutionService\x12U\n" +
	"\fExecuteTrade\x12!.execution.v1.ExecuteTradeRequest\x1a\".execution.v1.ExecuteTradeResponse\x12Y\n" +
	"\x12CancelPendingOrder\x12 .execution.v1.CancelOrderRequest\x1a!.execution.v1.CancelOrderResponse\x12R\n" +
	"\x11GetExecutionState\x12\x1d.execution.v1.GetStateRequest\x1a\x1e.execution.v1.GetStateResponseB>Z<github.com/flamegreat/etradie/proto/execution/v1;executionv1b\x06proto3"

var (
	file_execution_v1_execution_proto_rawDescOnce sync.Once
	file_execution_v1_execution_proto_rawDescData []byte
)

func file_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)))
	})
	return file_execution_v1_execution_proto_rawDescData
}

var file_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_execution_v1_execution_proto_goTypes = []any{
	(*ExecuteTradeRequest)(nil),  // 0: execution.v1.ExecuteTradeRequest
	(*ExecuteTradeResponse)(nil), // 1: execution.v1.ExecuteTradeResponse
	(*CancelOrderRequest)(nil),   // 2: execution.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),  // 3: execution.v1.CancelOrderResponse
	(*GetStateRequest)(nil),      // 4: execution.v1.GetStateRequest
	(*GetStateResponse)(nil),     // 5: execution.v1.GetStateResponse
	(*OpenPosition)(nil),         // 6: execution.v1.OpenPosition
	(*PendingOrder)(nil),         // 7: execution.v1.PendingOrder
}
var file_execution_v1_execution_proto_depIdxs = []int32{
	6, // 0: execution.v1.GetStateResponse.open_positions:type_name -> execution.v1.OpenPosition
	7, // 1: execution.v1.GetStateResponse.pending_orders:type_name -> execution.v1.PendingOrder
	0, // 2: execution.v1.ExecutionService.ExecuteTrade:input_type -> execution.v1.ExecuteTradeRequest
	2, // 3: execution.v1.ExecutionService.CancelPendingOrder:input_type -> execution.v1.CancelOrderRequest
	4, // 4: execution.v1.ExecutionService.GetExecutionState:input_type -> execution.v1.GetStateRequest
	1, // 5: execution.v1.ExecutionService.ExecuteTrade:output_type -> execution.v1.ExecuteTradeResponse
	3, // 6: execution.v1.ExecutionService.CancelPendingOrder:output_type -> execution.v1.CancelOrderResponse
	5, // 7: execution.v1.ExecutionService.GetExecutionState:output_type -> execution.v1.GetStateResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_execution_v1_execution_proto_init() }
func file_execution_v1_execution_proto_init() {
	if File_execution_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_execution_v1_execution_proto_depIdxs,
		MessageInfos:      file_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_execution_v1_execution_proto = out.File
	file_execution_v1_execution_proto_goTypes = nil
	file_execution_v1_execution_proto_depIdxs = nil
}
