// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: execution/v1/execution.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_ExecuteTrade_FullMethodName       = "/execution.v1.ExecutionService/ExecuteTrade"
	ExecutionService_CancelPendingOrder_FullMethodName = "/execution.v1.ExecutionService/CancelPendingOrder"
	ExecutionService_GetExecutionState_FullMethodName  = "/execution.v1.ExecutionService/GetExecutionState"
	ExecutionService_GetHaltState_FullMethodName       = "/execution.v1.ExecutionService/GetHaltState"
	ExecutionService_SetHaltState_FullMethodName       = "/execution.v1.ExecutionService/SetHaltState"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExecutionService is the gRPC contract between the Go gateway and
// the Module B execution engine. The gateway is the client; Module B
// implements this server. Triggered when a trade passes all guards.
type ExecutionServiceClient interface {
	// ExecuteTrade validates pre-execution checks, calculates position
	// size, and places the order (limit or instant mode).
	ExecuteTrade(ctx context.Context, in *ExecuteTradeRequest, opts ...grpc.CallOption) (*ExecuteTradeResponse, error)
	// CancelPendingOrder cancels a pending limit order or disarms an
	// instant-mode watcher. Called when structure breaks or thesis changes.
	CancelPendingOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// GetExecutionState returns current open positions, pending orders,
	// daily/weekly P&L, and concurrent trade count. Used by the dashboard
	// and by the gateway for pre-flight awareness.
	GetExecutionState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// GetHaltState reports the global and per-user execution kill-switch
	// flags (CHECKLIST Section 8). The gateway calls this in its routing
	// primary gate and to back the dashboard read. target_user_id selects
	// whose per-user flag to read; empty means "caller" (resolved by the
	// gateway from the JWT before the call).
	GetHaltState(ctx context.Context, in *GetHaltStateRequest, opts ...grpc.CallOption) (*GetHaltStateResponse, error)
	// SetHaltState engages or releases a kill switch (CHECKLIST Section 8).
	// Authorization is enforced server-side: SCOPE_GLOBAL requires the
	// caller to be an admin; SCOPE_USER requires the caller to be the
	// target user or an admin.
	SetHaltState(ctx context.Context, in *SetHaltStateRequest, opts ...grpc.CallOption) (*SetHaltStateResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) ExecuteTrade(ctx context.Context, in *ExecuteTradeRequest, opts ...grpc.CallOption) (*ExecuteTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTradeResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ExecuteTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) CancelPendingOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, ExecutionService_CancelPendingOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetExecutionState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetExecutionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetHaltState(ctx context.Context, in *GetHaltStateRequest, opts ...grpc.CallOption) (*GetHaltStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHaltStateResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetHaltState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) SetHaltState(ctx context.Context, in *SetHaltStateRequest, opts ...grpc.CallOption) (*SetHaltStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHaltStateResponse)
	err := c.cc.Invoke(ctx, ExecutionService_SetHaltState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// ExecutionService is the gRPC contract between the Go gateway and
// the Module B execution engine. The gateway is the client; Module B
// implements this server. Triggered when a trade passes all guards.
type ExecutionServiceServer interface {
	// ExecuteTrade validates pre-execution checks, calculates position
	// size, and places the order (limit or instant mode).
	ExecuteTrade(context.Context, *ExecuteTradeRequest) (*ExecuteTradeResponse, error)
	// CancelPendingOrder cancels a pending limit order or disarms an
	// instant-mode watcher. Called when structure breaks or thesis changes.
	CancelPendingOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// GetExecutionState returns current open positions, pending orders,
	// daily/weekly P&L, and concurrent trade count. Used by the dashboard
	// and by the gateway for pre-flight awareness.
	GetExecutionState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	// GetHaltState reports the global and per-user execution kill-switch
	// flags (CHECKLIST Section 8). The gateway calls this in its routing
	// primary gate and to back the dashboard read. target_user_id selects
	// whose per-user flag to read; empty means "caller" (resolved by the
	// gateway from the JWT before the call).
	GetHaltState(context.Context, *GetHaltStateRequest) (*GetHaltStateResponse, error)
	// SetHaltState engages or releases a kill switch (CHECKLIST Section 8).
	// Authorization is enforced server-side: SCOPE_GLOBAL requires the
	// caller to be an admin; SCOPE_USER requires the caller to be the
	// target user or an admin.
	SetHaltState(context.Context, *SetHaltStateRequest) (*SetHaltStateResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) ExecuteTrade(context.Context, *ExecuteTradeRequest) (*ExecuteTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTrade not implemented")
}
func (UnimplementedExecutionServiceServer) CancelPendingOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPendingOrder not implemented")
}
func (UnimplementedExecutionServiceServer) GetExecutionState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionState not implemented")
}
func (UnimplementedExecutionServiceServer) GetHaltState(context.Context, *GetHaltStateRequest) (*GetHaltStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHaltState not implemented")
}
func (UnimplementedExecutionServiceServer) SetHaltState(context.Context, *SetHaltStateRequest) (*SetHaltStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHaltState not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_ExecuteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ExecuteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ExecuteTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ExecuteTrade(ctx, req.(*ExecuteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_CancelPendingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).CancelPendingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_CancelPendingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).CancelPendingOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetExecutionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetExecutionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetExecutionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetExecutionState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetHaltState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHaltStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetHaltState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetHaltState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetHaltState(ctx, req.(*GetHaltStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_SetHaltState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHaltStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).SetHaltState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_SetHaltState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).SetHaltState(ctx, req.(*SetHaltStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTrade",
			Handler:    _ExecutionService_ExecuteTrade_Handler,
		},
		{
			MethodName: "CancelPendingOrder",
			Handler:    _ExecutionService_CancelPendingOrder_Handler,
		},
		{
			MethodName: "GetExecutionState",
			Handler:    _ExecutionService_GetExecutionState_Handler,
		},
		{
			MethodName: "GetHaltState",
			Handler:    _ExecutionService_GetHaltState_Handler,
		},
		{
			MethodName: "SetHaltState",
			Handler:    _ExecutionService_SetHaltState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution/v1/execution.proto",
}
