apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etradie-system

commonLabels:
  app.kubernetes.io/name: etradie-gateway
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: etradie
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - externalsecret.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml

images:
  - name: registry.gitlab.com/cotradee3/cotradeecode/gateway
    newTag: "0.1.0"