apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etradie-system

commonLabels:
  environment: local
  app.kubernetes.io/instance: local

commonAnnotations:
  managed-by: kustomize
  tier: local

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: etradie-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: HorizontalPodAutoscaler
      name: etradie-gateway
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: PodDisruptionBudget
      name: etradie-gateway
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1

images:
  - name: registry.gitlab.com/cotradee3/cotradeecode/gateway
    newTag: "local"

replicas:
  - name: etradie-gateway
    count: 1
