apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-ingress
spec:
  replicas: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-ingress
spec:
  minReplicas: 5
  maxReplicas: 15
