// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: management/v1/management.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterFilledTradeRequest carries everything Module C needs to take
// ownership of a filled trade. Maps from the Gateway's orchestration context.
type RegisterFilledTradeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction       string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`                                // "BUY" or "SELL"
	BrokerOrderId   string                 `protobuf:"bytes,3,opt,name=broker_order_id,json=brokerOrderId,proto3" json:"broker_order_id,omitempty"` // MT5 ticket number
	FillPrice       float64                `protobuf:"fixed64,4,opt,name=fill_price,json=fillPrice,proto3" json:"fill_price,omitempty"`             // Actual entry price at broker
	StopLoss        float64                `protobuf:"fixed64,5,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`                // Initial SL from Module A
	Tp1Price        float64                `protobuf:"fixed64,6,opt,name=tp1_price,json=tp1Price,proto3" json:"tp1_price,omitempty"`
	Tp1Pct          int32                  `protobuf:"varint,7,opt,name=tp1_pct,json=tp1Pct,proto3" json:"tp1_pct,omitempty"` // e.g. 40
	Tp2Price        float64                `protobuf:"fixed64,8,opt,name=tp2_price,json=tp2Price,proto3" json:"tp2_price,omitempty"`
	Tp2Pct          int32                  `protobuf:"varint,9,opt,name=tp2_pct,json=tp2Pct,proto3" json:"tp2_pct,omitempty"` // e.g. 30
	Tp3Price        float64                `protobuf:"fixed64,10,opt,name=tp3_price,json=tp3Price,proto3" json:"tp3_price,omitempty"`
	Tp3Pct          int32                  `protobuf:"varint,11,opt,name=tp3_pct,json=tp3Pct,proto3" json:"tp3_pct,omitempty"`     // e.g. 30
	LotSize         float64                `protobuf:"fixed64,12,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"` // Total filled lot size
	RrRatio         float64                `protobuf:"fixed64,13,opt,name=rr_ratio,json=rrRatio,proto3" json:"rr_ratio,omitempty"`
	RiskAmount      float64                `protobuf:"fixed64,14,opt,name=risk_amount,json=riskAmount,proto3" json:"risk_amount,omitempty"`     // Dollar risk at entry
	RiskPercent     float64                `protobuf:"fixed64,15,opt,name=risk_percent,json=riskPercent,proto3" json:"risk_percent,omitempty"`  // 1.0 or 0.5
	Grade           string                 `protobuf:"bytes,16,opt,name=grade,proto3" json:"grade,omitempty"`                                   // "A+", "A", "B"
	TradingStyle    string                 `protobuf:"bytes,17,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"` // "SCALPING", "INTRADAY", "SWING", "POSITIONAL"
	Session         string                 `protobuf:"bytes,18,opt,name=session,proto3" json:"session,omitempty"`                               // Session at time of entry
	ConfluenceScore float64                `protobuf:"fixed64,19,opt,name=confluence_score,json=confluenceScore,proto3" json:"confluence_score,omitempty"`
	AnalysisId      string                 `protobuf:"bytes,20,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"` // Links back to Module A output
	TraceId         string                 `protobuf:"bytes,21,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Slippage        float64                `protobuf:"fixed64,22,opt,name=slippage,proto3" json:"slippage,omitempty"`
	SetupType       string                 `protobuf:"bytes,23,opt,name=setup_type,json=setupType,proto3" json:"setup_type,omitempty"`             // "OB", "FVG", "SND_ZONE", "LIQUIDITY_SWEEP", etc.
	ExecutionMode   string                 `protobuf:"bytes,24,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"` // "LIMIT" or "INSTANT"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterFilledTradeRequest) Reset() {
	*x = RegisterFilledTradeRequest{}
	mi := &file_management_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFilledTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFilledTradeRequest) ProtoMessage() {}

func (x *RegisterFilledTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFilledTradeRequest.ProtoReflect.Descriptor instead.
func (*RegisterFilledTradeRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterFilledTradeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetBrokerOrderId() string {
	if x != nil {
		return x.BrokerOrderId
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetFillPrice() float64 {
	if x != nil {
		return x.FillPrice
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp1Price() float64 {
	if x != nil {
		return x.Tp1Price
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp1Pct() int32 {
	if x != nil {
		return x.Tp1Pct
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp2Price() float64 {
	if x != nil {
		return x.Tp2Price
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp2Pct() int32 {
	if x != nil {
		return x.Tp2Pct
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp3Price() float64 {
	if x != nil {
		return x.Tp3Price
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetTp3Pct() int32 {
	if x != nil {
		return x.Tp3Pct
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetLotSize() float64 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetRrRatio() float64 {
	if x != nil {
		return x.RrRatio
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetRiskAmount() float64 {
	if x != nil {
		return x.RiskAmount
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetRiskPercent() float64 {
	if x != nil {
		return x.RiskPercent
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetConfluenceScore() float64 {
	if x != nil {
		return x.ConfluenceScore
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetSlippage() float64 {
	if x != nil {
		return x.Slippage
	}
	return 0
}

func (x *RegisterFilledTradeRequest) GetSetupType() string {
	if x != nil {
		return x.SetupType
	}
	return ""
}

func (x *RegisterFilledTradeRequest) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

type RegisterFilledTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // Module C's internal trade tracking ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFilledTradeResponse) Reset() {
	*x = RegisterFilledTradeResponse{}
	mi := &file_management_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFilledTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFilledTradeResponse) ProtoMessage() {}

func (x *RegisterFilledTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFilledTradeResponse.ProtoReflect.Descriptor instead.
func (*RegisterFilledTradeResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterFilledTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterFilledTradeResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *RegisterFilledTradeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateTradeStatusRequest is sent by Module C back to the Gateway
// when significant trade events occur (TP hits, SL adjustments, closures).
type UpdateTradeStatusRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TradeId   string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	EventType string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "TP1_HIT", "TP2_HIT", "TP3_HIT", "SL_HIT", "BREAKEVEN_SET",
	// "TRAILING_SL_MOVED", "PARTIAL_CLOSE", "TRADE_CLOSED",
	// "EOD_CLOSURE", "INVALIDATION_CLOSURE"
	Symbol        string  `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CurrentPrice  float64 `protobuf:"fixed64,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	NewStopLoss   float64 `protobuf:"fixed64,5,opt,name=new_stop_loss,json=newStopLoss,proto3" json:"new_stop_loss,omitempty"`       // Updated SL (for BE/trail events)
	ClosedLotSize float64 `protobuf:"fixed64,6,opt,name=closed_lot_size,json=closedLotSize,proto3" json:"closed_lot_size,omitempty"` // For partial closes
	RealizedPnl   float64 `protobuf:"fixed64,7,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`         // P&L from partial or full close
	RMultiple     float64 `protobuf:"fixed64,8,opt,name=r_multiple,json=rMultiple,proto3" json:"r_multiple,omitempty"`               // Realized R-multiple
	Reason        string  `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`                                        // Human-readable reason
	TraceId       string  `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTradeStatusRequest) Reset() {
	*x = UpdateTradeStatusRequest{}
	mi := &file_management_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeStatusRequest) ProtoMessage() {}

func (x *UpdateTradeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTradeStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTradeStatusRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *UpdateTradeStatusRequest) GetNewStopLoss() float64 {
	if x != nil {
		return x.NewStopLoss
	}
	return 0
}

func (x *UpdateTradeStatusRequest) GetClosedLotSize() float64 {
	if x != nil {
		return x.ClosedLotSize
	}
	return 0
}

func (x *UpdateTradeStatusRequest) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *UpdateTradeStatusRequest) GetRMultiple() float64 {
	if x != nil {
		return x.RMultiple
	}
	return 0
}

func (x *UpdateTradeStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type UpdateTradeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTradeStatusResponse) Reset() {
	*x = UpdateTradeStatusResponse{}
	mi := &file_management_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeStatusResponse) ProtoMessage() {}

func (x *UpdateTradeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTradeStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTradeStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetManagedTradesRequest retrieves all actively managed trades.
type GetManagedTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedTradesRequest) Reset() {
	*x = GetManagedTradesRequest{}
	mi := &file_management_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedTradesRequest) ProtoMessage() {}

func (x *GetManagedTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedTradesRequest.ProtoReflect.Descriptor instead.
func (*GetManagedTradesRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetManagedTradesRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetManagedTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*ManagedTrade        `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedTradesResponse) Reset() {
	*x = GetManagedTradesResponse{}
	mi := &file_management_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedTradesResponse) ProtoMessage() {}

func (x *GetManagedTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedTradesResponse.ProtoReflect.Descriptor instead.
func (*GetManagedTradesResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetManagedTradesResponse) GetTrades() []*ManagedTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type ManagedTrade struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TradeId          string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction        string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	EntryPrice       float64                `protobuf:"fixed64,4,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	CurrentPrice     float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	StopLoss         float64                `protobuf:"fixed64,6,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	Tp1Price         float64                `protobuf:"fixed64,7,opt,name=tp1_price,json=tp1Price,proto3" json:"tp1_price,omitempty"`
	Tp2Price         float64                `protobuf:"fixed64,8,opt,name=tp2_price,json=tp2Price,proto3" json:"tp2_price,omitempty"`
	Tp3Price         float64                `protobuf:"fixed64,9,opt,name=tp3_price,json=tp3Price,proto3" json:"tp3_price,omitempty"`
	TotalLotSize     float64                `protobuf:"fixed64,10,opt,name=total_lot_size,json=totalLotSize,proto3" json:"total_lot_size,omitempty"`
	RemainingLotSize float64                `protobuf:"fixed64,11,opt,name=remaining_lot_size,json=remainingLotSize,proto3" json:"remaining_lot_size,omitempty"`
	UnrealizedPnl    float64                `protobuf:"fixed64,12,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	RealizedPnl      float64                `protobuf:"fixed64,13,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	TradingStyle     string                 `protobuf:"bytes,14,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"`
	Status           string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"` // "ACTIVE", "BREAKEVEN", "TRAILING", "CLOSING"
	BreakevenSet     bool                   `protobuf:"varint,16,opt,name=breakeven_set,json=breakevenSet,proto3" json:"breakeven_set,omitempty"`
	Tp1Hit           bool                   `protobuf:"varint,17,opt,name=tp1_hit,json=tp1Hit,proto3" json:"tp1_hit,omitempty"`
	Tp2Hit           bool                   `protobuf:"varint,18,opt,name=tp2_hit,json=tp2Hit,proto3" json:"tp2_hit,omitempty"`
	BrokerOrderId    string                 `protobuf:"bytes,19,opt,name=broker_order_id,json=brokerOrderId,proto3" json:"broker_order_id,omitempty"`
	AnalysisId       string                 `protobuf:"bytes,20,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	OpenedAt         string                 `protobuf:"bytes,21,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManagedTrade) Reset() {
	*x = ManagedTrade{}
	mi := &file_management_v1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedTrade) ProtoMessage() {}

func (x *ManagedTrade) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedTrade.ProtoReflect.Descriptor instead.
func (*ManagedTrade) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{6}
}

func (x *ManagedTrade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *ManagedTrade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ManagedTrade) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ManagedTrade) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *ManagedTrade) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *ManagedTrade) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *ManagedTrade) GetTp1Price() float64 {
	if x != nil {
		return x.Tp1Price
	}
	return 0
}

func (x *ManagedTrade) GetTp2Price() float64 {
	if x != nil {
		return x.Tp2Price
	}
	return 0
}

func (x *ManagedTrade) GetTp3Price() float64 {
	if x != nil {
		return x.Tp3Price
	}
	return 0
}

func (x *ManagedTrade) GetTotalLotSize() float64 {
	if x != nil {
		return x.TotalLotSize
	}
	return 0
}

func (x *ManagedTrade) GetRemainingLotSize() float64 {
	if x != nil {
		return x.RemainingLotSize
	}
	return 0
}

func (x *ManagedTrade) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *ManagedTrade) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *ManagedTrade) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

func (x *ManagedTrade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ManagedTrade) GetBreakevenSet() bool {
	if x != nil {
		return x.BreakevenSet
	}
	return false
}

func (x *ManagedTrade) GetTp1Hit() bool {
	if x != nil {
		return x.Tp1Hit
	}
	return false
}

func (x *ManagedTrade) GetTp2Hit() bool {
	if x != nil {
		return x.Tp2Hit
	}
	return false
}

func (x *ManagedTrade) GetBrokerOrderId() string {
	if x != nil {
		return x.BrokerOrderId
	}
	return ""
}

func (x *ManagedTrade) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *ManagedTrade) GetOpenedAt() string {
	if x != nil {
		return x.OpenedAt
	}
	return ""
}

// GetTradeJournalRequest retrieves closed trade journal entries.
type GetTradeJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Max entries to return (default 50)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                                // Pagination offset
	SymbolFilter  string                 `protobuf:"bytes,3,opt,name=symbol_filter,json=symbolFilter,proto3" json:"symbol_filter,omitempty"` // Optional: filter by symbol
	StyleFilter   string                 `protobuf:"bytes,4,opt,name=style_filter,json=styleFilter,proto3" json:"style_filter,omitempty"`    // Optional: filter by trading style
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeJournalRequest) Reset() {
	*x = GetTradeJournalRequest{}
	mi := &file_management_v1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeJournalRequest) ProtoMessage() {}

func (x *GetTradeJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeJournalRequest.ProtoReflect.Descriptor instead.
func (*GetTradeJournalRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{7}
}

func (x *GetTradeJournalRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTradeJournalRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTradeJournalRequest) GetSymbolFilter() string {
	if x != nil {
		return x.SymbolFilter
	}
	return ""
}

func (x *GetTradeJournalRequest) GetStyleFilter() string {
	if x != nil {
		return x.StyleFilter
	}
	return ""
}

func (x *GetTradeJournalRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetTradeJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JournalEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeJournalResponse) Reset() {
	*x = GetTradeJournalResponse{}
	mi := &file_management_v1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeJournalResponse) ProtoMessage() {}

func (x *GetTradeJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeJournalResponse.ProtoReflect.Descriptor instead.
func (*GetTradeJournalResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetTradeJournalResponse) GetEntries() []*JournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetTradeJournalResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type JournalEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TradeId           string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Direction         string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	EntryPrice        float64                `protobuf:"fixed64,4,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitPrice         float64                `protobuf:"fixed64,5,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	StopLoss          float64                `protobuf:"fixed64,6,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	LotSize           float64                `protobuf:"fixed64,7,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	GrossPnl          float64                `protobuf:"fixed64,8,opt,name=gross_pnl,json=grossPnl,proto3" json:"gross_pnl,omitempty"`
	RMultiple         float64                `protobuf:"fixed64,9,opt,name=r_multiple,json=rMultiple,proto3" json:"r_multiple,omitempty"`
	ConfluenceScore   float64                `protobuf:"fixed64,10,opt,name=confluence_score,json=confluenceScore,proto3" json:"confluence_score,omitempty"`
	Grade             string                 `protobuf:"bytes,11,opt,name=grade,proto3" json:"grade,omitempty"`
	SetupType         string                 `protobuf:"bytes,12,opt,name=setup_type,json=setupType,proto3" json:"setup_type,omitempty"`
	TradingStyle      string                 `protobuf:"bytes,13,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"`
	Outcome           string                 `protobuf:"bytes,14,opt,name=outcome,proto3" json:"outcome,omitempty"` // "WIN", "LOSS", "BREAKEVEN"
	OpenedAt          string                 `protobuf:"bytes,15,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	ClosedAt          string                 `protobuf:"bytes,16,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	DurationMinutes   int32                  `protobuf:"varint,17,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	SlAdjustmentCount int32                  `protobuf:"varint,18,opt,name=sl_adjustment_count,json=slAdjustmentCount,proto3" json:"sl_adjustment_count,omitempty"`
	PartialCloseCount int32                  `protobuf:"varint,19,opt,name=partial_close_count,json=partialCloseCount,proto3" json:"partial_close_count,omitempty"`
	AnalysisId        string                 `protobuf:"bytes,20,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_management_v1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{9}
}

func (x *JournalEntry) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *JournalEntry) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *JournalEntry) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *JournalEntry) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *JournalEntry) GetExitPrice() float64 {
	if x != nil {
		return x.ExitPrice
	}
	return 0
}

func (x *JournalEntry) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *JournalEntry) GetLotSize() float64 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *JournalEntry) GetGrossPnl() float64 {
	if x != nil {
		return x.GrossPnl
	}
	return 0
}

func (x *JournalEntry) GetRMultiple() float64 {
	if x != nil {
		return x.RMultiple
	}
	return 0
}

func (x *JournalEntry) GetConfluenceScore() float64 {
	if x != nil {
		return x.ConfluenceScore
	}
	return 0
}

func (x *JournalEntry) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *JournalEntry) GetSetupType() string {
	if x != nil {
		return x.SetupType
	}
	return ""
}

func (x *JournalEntry) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

func (x *JournalEntry) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *JournalEntry) GetOpenedAt() string {
	if x != nil {
		return x.OpenedAt
	}
	return ""
}

func (x *JournalEntry) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *JournalEntry) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *JournalEntry) GetSlAdjustmentCount() int32 {
	if x != nil {
		return x.SlAdjustmentCount
	}
	return 0
}

func (x *JournalEntry) GetPartialCloseCount() int32 {
	if x != nil {
		return x.PartialCloseCount
	}
	return 0
}

func (x *JournalEntry) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

// GetPerformanceMetricsRequest retrieves real-time analytics.
type GetPerformanceMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // "DAILY", "WEEKLY", "MONTHLY", "ALL_TIME"
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceMetricsRequest) Reset() {
	*x = GetPerformanceMetricsRequest{}
	mi := &file_management_v1_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceMetricsRequest) ProtoMessage() {}

func (x *GetPerformanceMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetPerformanceMetricsRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetPerformanceMetricsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetPerformanceMetricsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetPerformanceMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WinRate              float64                `protobuf:"fixed64,1,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	AvgRMultiple         float64                `protobuf:"fixed64,2,opt,name=avg_r_multiple,json=avgRMultiple,proto3" json:"avg_r_multiple,omitempty"`
	Expectancy           float64                `protobuf:"fixed64,3,opt,name=expectancy,proto3" json:"expectancy,omitempty"`
	TotalTrades          int32                  `protobuf:"varint,4,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	Wins                 int32                  `protobuf:"varint,5,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses               int32                  `protobuf:"varint,6,opt,name=losses,proto3" json:"losses,omitempty"`
	Breakevens           int32                  `protobuf:"varint,7,opt,name=breakevens,proto3" json:"breakevens,omitempty"`
	TotalPnl             float64                `protobuf:"fixed64,8,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	MaxConsecutiveWins   int32                  `protobuf:"varint,9,opt,name=max_consecutive_wins,json=maxConsecutiveWins,proto3" json:"max_consecutive_wins,omitempty"`
	MaxConsecutiveLosses int32                  `protobuf:"varint,10,opt,name=max_consecutive_losses,json=maxConsecutiveLosses,proto3" json:"max_consecutive_losses,omitempty"`
	MaxDrawdownPct       float64                `protobuf:"fixed64,11,opt,name=max_drawdown_pct,json=maxDrawdownPct,proto3" json:"max_drawdown_pct,omitempty"`
	BestTradeR           float64                `protobuf:"fixed64,12,opt,name=best_trade_r,json=bestTradeR,proto3" json:"best_trade_r,omitempty"`
	WorstTradeR          float64                `protobuf:"fixed64,13,opt,name=worst_trade_r,json=worstTradeR,proto3" json:"worst_trade_r,omitempty"`
	WinRateBySymbol      map[string]float64     `protobuf:"bytes,14,rep,name=win_rate_by_symbol,json=winRateBySymbol,proto3" json:"win_rate_by_symbol,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	WinRateByStyle       map[string]float64     `protobuf:"bytes,15,rep,name=win_rate_by_style,json=winRateByStyle,proto3" json:"win_rate_by_style,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	WinRateBySetup       map[string]float64     `protobuf:"bytes,16,rep,name=win_rate_by_setup,json=winRateBySetup,proto3" json:"win_rate_by_setup,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	WinRateBySession     map[string]float64     `protobuf:"bytes,17,rep,name=win_rate_by_session,json=winRateBySession,proto3" json:"win_rate_by_session,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPerformanceMetricsResponse) Reset() {
	*x = GetPerformanceMetricsResponse{}
	mi := &file_management_v1_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceMetricsResponse) ProtoMessage() {}

func (x *GetPerformanceMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetPerformanceMetricsResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetPerformanceMetricsResponse) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetAvgRMultiple() float64 {
	if x != nil {
		return x.AvgRMultiple
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetExpectancy() float64 {
	if x != nil {
		return x.Expectancy
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetBreakevens() int32 {
	if x != nil {
		return x.Breakevens
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetTotalPnl() float64 {
	if x != nil {
		return x.TotalPnl
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetMaxConsecutiveWins() int32 {
	if x != nil {
		return x.MaxConsecutiveWins
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetMaxConsecutiveLosses() int32 {
	if x != nil {
		return x.MaxConsecutiveLosses
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetMaxDrawdownPct() float64 {
	if x != nil {
		return x.MaxDrawdownPct
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetBestTradeR() float64 {
	if x != nil {
		return x.BestTradeR
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetWorstTradeR() float64 {
	if x != nil {
		return x.WorstTradeR
	}
	return 0
}

func (x *GetPerformanceMetricsResponse) GetWinRateBySymbol() map[string]float64 {
	if x != nil {
		return x.WinRateBySymbol
	}
	return nil
}

func (x *GetPerformanceMetricsResponse) GetWinRateByStyle() map[string]float64 {
	if x != nil {
		return x.WinRateByStyle
	}
	return nil
}

func (x *GetPerformanceMetricsResponse) GetWinRateBySetup() map[string]float64 {
	if x != nil {
		return x.WinRateBySetup
	}
	return nil
}

func (x *GetPerformanceMetricsResponse) GetWinRateBySession() map[string]float64 {
	if x != nil {
		return x.WinRateBySession
	}
	return nil
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_management_v1_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{12}
}

type GetHealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" | "degraded"
	DbConnected     bool                   `protobuf:"varint,2,opt,name=db_connected,json=dbConnected,proto3" json:"db_connected,omitempty"`
	BrokerConnected bool                   `protobuf:"varint,3,opt,name=broker_connected,json=brokerConnected,proto3" json:"broker_connected,omitempty"`
	ActiveTrades    int32                  `protobuf:"varint,4,opt,name=active_trades,json=activeTrades,proto3" json:"active_trades,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_management_v1_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{13}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetDbConnected() bool {
	if x != nil {
		return x.DbConnected
	}
	return false
}

func (x *GetHealthResponse) GetBrokerConnected() bool {
	if x != nil {
		return x.BrokerConnected
	}
	return false
}

func (x *GetHealthResponse) GetActiveTrades() int32 {
	if x != nil {
		return x.ActiveTrades
	}
	return 0
}

var File_management_v1_management_proto protoreflect.FileDescriptor

const file_management_v1_management_proto_rawDesc = "" +
	"\n" +
	"\x1emanagement/v1/management.proto\x12\rmanagement.v1\"\xf0\x05\n" +
	"\x1aRegisterFilledTradeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12&\n" +
	"\x0fbroker_order_id\x18\x03 \x01(\tR\rbrokerOrderId\x12\x1d\n" +
	"\n" +
	"fill_price\x18\x04 \x01(\x01R\tfillPrice\x12\x1b\n" +
	"\tstop_loss\x18\x05 \x01(\x01R\bstopLoss\x12\x1b\n" +
	"\ttp1_price\x18\x06 \x01(\x01R\btp1Price\x12\x17\n" +
	"\atp1_pct\x18\a \x01(\x05R\x06tp1Pct\x12\x1b\n" +
	"\ttp2_price\x18\b \x01(\x01R\btp2Price\x12\x17\n" +
	"\atp2_pct\x18\t \x01(\x05R\x06tp2Pct\x12\x1b\n" +
	"\ttp3_price\x18\n" +
	" \x01(\x01R\btp3Price\x12\x17\n" +
	"\atp3_pct\x18\v \x01(\x05R\x06tp3Pct\x12\x19\n" +
	"\blot_size\x18\f \x01(\x01R\alotSize\x12\x19\n" +
	"\brr_ratio\x18\r \x01(\x01R\arrRatio\x12\x1f\n" +
	"\vrisk_amount\x18\x0e \x01(\x01R\n" +
	"riskAmount\x12!\n" +
	"\frisk_percent\x18\x0f \x01(\x01R\vriskPercent\x12\x14\n" +
	"\x05grade\x18\x10 \x01(\tR\x05grade\x12#\n" +
	"\rtrading_style\x18\x11 \x01(\tR\ftradingStyle\x12\x18\n" +
	"\asession\x18\x12 \x01(\tR\asession\x12)\n" +
	"\x10confluence_score\x18\x13 \x01(\x01R\x0fconfluenceScore\x12\x1f\n" +
	"\vanalysis_id\x18\x14 \x01(\tR\n" +
	"analysisId\x12\x19\n" +
	"\btrace_id\x18\x15 \x01(\tR\atraceId\x12\x1a\n" +
	"\bslippage\x18\x16 \x01(\x01R\bslippage\x12\x1d\n" +
	"\n" +
	"setup_type\x18\x17 \x01(\tR\tsetupType\x12%\n" +
	"\x0eexecution_mode\x18\x18 \x01(\tR\rexecutionMode\"l\n" +
	"\x1bRegisterFilledTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd2\x02\n" +
	"\x18UpdateTradeStatusRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x01R\fcurrentPrice\x12\"\n" +
	"\rnew_stop_loss\x18\x05 \x01(\x01R\vnewStopLoss\x12&\n" +
	"\x0fclosed_lot_size\x18\x06 \x01(\x01R\rclosedLotSize\x12!\n" +
	"\frealized_pnl\x18\a \x01(\x01R\vrealizedPnl\x12\x1d\n" +
	"\n" +
	"r_multiple\x18\b \x01(\x01R\trMultiple\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"5\n" +
	"\x19UpdateTradeStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x17GetManagedTradesRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"O\n" +
	"\x18GetManagedTradesResponse\x123\n" +
	"\x06trades\x18\x01 \x03(\v2\x1b.management.v1.ManagedTradeR\x06trades\"\xb1\x05\n" +
	"\fManagedTrade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1f\n" +
	"\ventry_price\x18\x04 \x01(\x01R\n" +
	"entryPrice\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\x12\x1b\n" +
	"\tstop_loss\x18\x06 \x01(\x01R\bstopLoss\x12\x1b\n" +
	"\ttp1_price\x18\a \x01(\x01R\btp1Price\x12\x1b\n" +
	"\ttp2_price\x18\b \x01(\x01R\btp2Price\x12\x1b\n" +
	"\ttp3_price\x18\t \x01(\x01R\btp3Price\x12$\n" +
	"\x0etotal_lot_size\x18\n" +
	" \x01(\x01R\ftotalLotSize\x12,\n" +
	"\x12remaining_lot_size\x18\v \x01(\x01R\x10remainingLotSize\x12%\n" +
	"\x0eunrealized_pnl\x18\f \x01(\x01R\runrealizedPnl\x12!\n" +
	"\frealized_pnl\x18\r \x01(\x01R\vrealizedPnl\x12#\n" +
	"\rtrading_style\x18\x0e \x01(\tR\ftradingStyle\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12#\n" +
	"\rbreakeven_set\x18\x10 \x01(\bR\fbreakevenSet\x12\x17\n" +
	"\atp1_hit\x18\x11 \x01(\bR\x06tp1Hit\x12\x17\n" +
	"\atp2_hit\x18\x12 \x01(\bR\x06tp2Hit\x12&\n" +
	"\x0fbroker_order_id\x18\x13 \x01(\tR\rbrokerOrderId\x12\x1f\n" +
	"\vanalysis_id\x18\x14 \x01(\tR\n" +
	"analysisId\x12\x1b\n" +
	"\topened_at\x18\x15 \x01(\tR\bopenedAt\"\xa9\x01\n" +
	"\x16GetTradeJournalRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12#\n" +
	"\rsymbol_filter\x18\x03 \x01(\tR\fsymbolFilter\x12!\n" +
	"\fstyle_filter\x18\x04 \x01(\tR\vstyleFilter\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"q\n" +
	"\x17GetTradeJournalResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.management.v1.JournalEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x98\x05\n" +
	"\fJournalEntry\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1f\n" +
	"\ventry_price\x18\x04 \x01(\x01R\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"exit_price\x18\x05 \x01(\x01R\texitPrice\x12\x1b\n" +
	"\tstop_loss\x18\x06 \x01(\x01R\bstopLoss\x12\x19\n" +
	"\blot_size\x18\a \x01(\x01R\alotSize\x12\x1b\n" +
	"\tgross_pnl\x18\b \x01(\x01R\bgrossPnl\x12\x1d\n" +
	"\n" +
	"r_multiple\x18\t \x01(\x01R\trMultiple\x12)\n" +
	"\x10confluence_score\x18\n" +
	" \x01(\x01R\x0fconfluenceScore\x12\x14\n" +
	"\x05grade\x18\v \x01(\tR\x05grade\x12\x1d\n" +
	"\n" +
	"setup_type\x18\f \x01(\tR\tsetupType\x12#\n" +
	"\rtrading_style\x18\r \x01(\tR\ftradingStyle\x12\x18\n" +
	"\aoutcome\x18\x0e \x01(\tR\aoutcome\x12\x1b\n" +
	"\topened_at\x18\x0f \x01(\tR\bopenedAt\x12\x1b\n" +
	"\tclosed_at\x18\x10 \x01(\tR\bclosedAt\x12)\n" +
	"\x10duration_minutes\x18\x11 \x01(\x05R\x0fdurationMinutes\x12.\n" +
	"\x13sl_adjustment_count\x18\x12 \x01(\x05R\x11slAdjustmentCount\x12.\n" +
	"\x13partial_close_count\x18\x13 \x01(\x05R\x11partialCloseCount\x12\x1f\n" +
	"\vanalysis_id\x18\x14 \x01(\tR\n" +
	"analysisId\"Q\n" +
	"\x1cGetPerformanceMetricsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\xb0\t\n" +
	"\x1dGetPerformanceMetricsResponse\x12\x19\n" +
	"\bwin_rate\x18\x01 \x01(\x01R\awinRate\x12$\n" +
	"\x0eavg_r_multiple\x18\x02 \x01(\x01R\favgRMultiple\x12\x1e\n" +
	"\n" +
	"expectancy\x18\x03 \x01(\x01R\n" +
	"expectancy\x12!\n" +
	"\ftotal_trades\x18\x04 \x01(\x05R\vtotalTrades\x12\x12\n" +
	"\x04wins\x18\x05 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x06 \x01(\x05R\x06losses\x12\x1e\n" +
	"\n" +
	"breakevens\x18\a \x01(\x05R\n" +
	"breakevens\x12\x1b\n" +
	"\ttotal_pnl\x18\b \x01(\x01R\btotalPnl\x120\n" +
	"\x14max_consecutive_wins\x18\t \x01(\x05R\x12maxConsecutiveWins\x124\n" +
	"\x16max_consecutive_losses\x18\n" +
	" \x01(\x05R\x14maxConsecutiveLosses\x12(\n" +
	"\x10max_drawdown_pct\x18\v \x01(\x01R\x0emaxDrawdownPct\x12 \n" +
	"\fbest_trade_r\x18\f \x01(\x01R\n" +
	"bestTradeR\x12\"\n" +
	"\rworst_trade_r\x18\r \x01(\x01R\vworstTradeR\x12n\n" +
	"\x12win_rate_by_symbol\x18\x0e \x03(\v2A.management.v1.GetPerformanceMetricsResponse.WinRateBySymbolEntryR\x0fwinRateBySymbol\x12k\n" +
	"\x11win_rate_by_style\x18\x0f \x03(\v2@.management.v1.GetPerformanceMetricsResponse.WinRateByStyleEntryR\x0ewinRateByStyle\x12k\n" +
	"\x11win_rate_by_setup\x18\x10 \x03(\v2@.management.v1.GetPerformanceMetricsResponse.WinRateBySetupEntryR\x0ewinRateBySetup\x12q\n" +
	"\x13win_rate_by_session\x18\x11 \x03(\v2B.management.v1.GetPerformanceMetricsResponse.WinRateBySessionEntryR\x10winRateBySession\x1aB\n" +
	"\x14WinRateBySymbolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aA\n" +
	"\x13WinRateByStyleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aA\n" +
	"\x13WinRateBySetupEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aC\n" +
	"\x15WinRateBySessionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x12\n" +
	"\x10GetHealthRequest\"\x9e\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fdb_connected\x18\x02 \x01(\bR\vdbConnected\x12)\n" +
	"\x10broker_connected\x18\x03 \x01(\bR\x0fbrokerConnected\x12#\n" +
	"\ractive_trades\x18\x04 \x01(\x05R\factiveTrades2\xf4\x04\n" +
	"\x11ManagementService\x12l\n" +
	"\x13RegisterFilledTrade\x12).management.v1.RegisterFilledTradeRequest\x1a*.management.v1.RegisterFilledTradeResponse\x12f\n" +
	"\x11UpdateTradeStatus\x12'.management.v1.UpdateTradeStatusRequest\x1a(.management.v1.UpdateTradeStatusResponse\x12c\n" +
	"\x10GetManagedTrades\x12&.management.v1.GetManagedTradesRequest\x1a'.management.v1.GetManagedTradesResponse\x12`\n" +
	"\x0fGetTradeJournal\x12%.management.v1.GetTradeJournalRequest\x1a&.management.v1.GetTradeJournalResponse\x12r\n" +
	"\x15GetPerformanceMetrics\x12+.management.v1.GetPerformanceMetricsRequest\x1a,.management.v1.GetPerformanceMetricsResponse\x12N\n" +
	"\tGetHealth\x12\x1f.management.v1.GetHealthRequest\x1a .management.v1.GetHealthResponseBBZ@github.com/flamegreat-1/etradie/proto/management/v1;managementv1b\x06proto3"

var (
	file_management_v1_management_proto_rawDescOnce sync.Once
	file_management_v1_management_proto_rawDescData []byte
)

func file_management_v1_management_proto_rawDescGZIP() []byte {
	file_management_v1_management_proto_rawDescOnce.Do(func() {
		file_management_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_v1_management_proto_rawDesc), len(file_management_v1_management_proto_rawDesc)))
	})
	return file_management_v1_management_proto_rawDescData
}

var file_management_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_management_v1_management_proto_goTypes = []any{
	(*RegisterFilledTradeRequest)(nil),    // 0: management.v1.RegisterFilledTradeRequest
	(*RegisterFilledTradeResponse)(nil),   // 1: management.v1.RegisterFilledTradeResponse
	(*UpdateTradeStatusRequest)(nil),      // 2: management.v1.UpdateTradeStatusRequest
	(*UpdateTradeStatusResponse)(nil),     // 3: management.v1.UpdateTradeStatusResponse
	(*GetManagedTradesRequest)(nil),       // 4: management.v1.GetManagedTradesRequest
	(*GetManagedTradesResponse)(nil),      // 5: management.v1.GetManagedTradesResponse
	(*ManagedTrade)(nil),                  // 6: management.v1.ManagedTrade
	(*GetTradeJournalRequest)(nil),        // 7: management.v1.GetTradeJournalRequest
	(*GetTradeJournalResponse)(nil),       // 8: management.v1.GetTradeJournalResponse
	(*JournalEntry)(nil),                  // 9: management.v1.JournalEntry
	(*GetPerformanceMetricsRequest)(nil),  // 10: management.v1.GetPerformanceMetricsRequest
	(*GetPerformanceMetricsResponse)(nil), // 11: management.v1.GetPerformanceMetricsResponse
	(*GetHealthRequest)(nil),              // 12: management.v1.GetHealthRequest
	(*GetHealthResponse)(nil),             // 13: management.v1.GetHealthResponse
	nil,                                   // 14: management.v1.GetPerformanceMetricsResponse.WinRateBySymbolEntry
	nil,                                   // 15: management.v1.GetPerformanceMetricsResponse.WinRateByStyleEntry
	nil,                                   // 16: management.v1.GetPerformanceMetricsResponse.WinRateBySetupEntry
	nil,                                   // 17: management.v1.GetPerformanceMetricsResponse.WinRateBySessionEntry
}
var file_management_v1_management_proto_depIdxs = []int32{
	6,  // 0: management.v1.GetManagedTradesResponse.trades:type_name -> management.v1.ManagedTrade
	9,  // 1: management.v1.GetTradeJournalResponse.entries:type_name -> management.v1.JournalEntry
	14, // 2: management.v1.GetPerformanceMetricsResponse.win_rate_by_symbol:type_name -> management.v1.GetPerformanceMetricsResponse.WinRateBySymbolEntry
	15, // 3: management.v1.GetPerformanceMetricsResponse.win_rate_by_style:type_name -> management.v1.GetPerformanceMetricsResponse.WinRateByStyleEntry
	16, // 4: management.v1.GetPerformanceMetricsResponse.win_rate_by_setup:type_name -> management.v1.GetPerformanceMetricsResponse.WinRateBySetupEntry
	17, // 5: management.v1.GetPerformanceMetricsResponse.win_rate_by_session:type_name -> management.v1.GetPerformanceMetricsResponse.WinRateBySessionEntry
	0,  // 6: management.v1.ManagementService.RegisterFilledTrade:input_type -> management.v1.RegisterFilledTradeRequest
	2,  // 7: management.v1.ManagementService.UpdateTradeStatus:input_type -> management.v1.UpdateTradeStatusRequest
	4,  // 8: management.v1.ManagementService.GetManagedTrades:input_type -> management.v1.GetManagedTradesRequest
	7,  // 9: management.v1.ManagementService.GetTradeJournal:input_type -> management.v1.GetTradeJournalRequest
	10, // 10: management.v1.ManagementService.GetPerformanceMetrics:input_type -> management.v1.GetPerformanceMetricsRequest
	12, // 11: management.v1.ManagementService.GetHealth:input_type -> management.v1.GetHealthRequest
	1,  // 12: management.v1.ManagementService.RegisterFilledTrade:output_type -> management.v1.RegisterFilledTradeResponse
	3,  // 13: management.v1.ManagementService.UpdateTradeStatus:output_type -> management.v1.UpdateTradeStatusResponse
	5,  // 14: management.v1.ManagementService.GetManagedTrades:output_type -> management.v1.GetManagedTradesResponse
	8,  // 15: management.v1.ManagementService.GetTradeJournal:output_type -> management.v1.GetTradeJournalResponse
	11, // 16: management.v1.ManagementService.GetPerformanceMetrics:output_type -> management.v1.GetPerformanceMetricsResponse
	13, // 17: management.v1.ManagementService.GetHealth:output_type -> management.v1.GetHealthResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_management_v1_management_proto_init() }
func file_management_v1_management_proto_init() {
	if File_management_v1_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_management_proto_rawDesc), len(file_management_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_v1_management_proto_goTypes,
		DependencyIndexes: file_management_v1_management_proto_depIdxs,
		MessageInfos:      file_management_v1_management_proto_msgTypes,
	}.Build()
	File_management_v1_management_proto = out.File
	file_management_v1_management_proto_goTypes = nil
	file_management_v1_management_proto_depIdxs = nil
}
