// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: management/v1/management.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_RegisterFilledTrade_FullMethodName   = "/management.v1.ManagementService/RegisterFilledTrade"
	ManagementService_UpdateTradeStatus_FullMethodName     = "/management.v1.ManagementService/UpdateTradeStatus"
	ManagementService_GetManagedTrades_FullMethodName      = "/management.v1.ManagementService/GetManagedTrades"
	ManagementService_GetTradeJournal_FullMethodName       = "/management.v1.ManagementService/GetTradeJournal"
	ManagementService_GetPerformanceMetrics_FullMethodName = "/management.v1.ManagementService/GetPerformanceMetrics"
	ManagementService_GetHealth_FullMethodName             = "/management.v1.ManagementService/GetHealth"
	ManagementService_GetManualJournal_FullMethodName      = "/management.v1.ManagementService/GetManualJournal"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagementService is the gRPC contract for Module C (Trade Management).
// The Gateway is the primary client. Module C implements this server.
// Triggered when a trade is FILLED at the broker (Step 7 of the architecture).
type ManagementServiceClient interface {
	// RegisterFilledTrade is called by the Gateway immediately after the
	// Execution service confirms an order is FILLED. This transfers full
	// ownership of the trade to Module C for lifecycle management:
	// break-even, trailing, partial closes, EOD protocols, and journaling.
	RegisterFilledTrade(ctx context.Context, in *RegisterFilledTradeRequest, opts ...grpc.CallOption) (*RegisterFilledTradeResponse, error)
	// UpdateTradeStatus allows Module C to report TP/SL hits, partial
	// closes, and final closures back to the Gateway for orchestration
	// awareness and dashboard visibility.
	UpdateTradeStatus(ctx context.Context, in *UpdateTradeStatusRequest, opts ...grpc.CallOption) (*UpdateTradeStatusResponse, error)
	// GetManagedTrades returns all trades currently under Module C management.
	GetManagedTrades(ctx context.Context, in *GetManagedTradesRequest, opts ...grpc.CallOption) (*GetManagedTradesResponse, error)
	// GetTradeJournal returns closed trade history with full journal detail.
	GetTradeJournal(ctx context.Context, in *GetTradeJournalRequest, opts ...grpc.CallOption) (*GetTradeJournalResponse, error)
	// GetPerformanceMetrics returns real-time analytics (win rate, expectancy, etc.).
	GetPerformanceMetrics(ctx context.Context, in *GetPerformanceMetricsRequest, opts ...grpc.CallOption) (*GetPerformanceMetricsResponse, error)
	// GetHealth returns the management service's health status.
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// GetManualJournal returns the user's manually-executed / reconciled
	// trades (origin = MANUAL_RECONCILED) within a time window, BOTH open
	// and closed. It powers the 90-Day Trading Plan's Daily Execution
	// Journal auto-populate: the gateway composites these objective facts
	// with the trader's saved subjective annotations. System-executed
	// trades and rough MANUAL_RESTORED history rows are excluded.
	GetManualJournal(ctx context.Context, in *GetManualJournalRequest, opts ...grpc.CallOption) (*GetManualJournalResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) RegisterFilledTrade(ctx context.Context, in *RegisterFilledTradeRequest, opts ...grpc.CallOption) (*RegisterFilledTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFilledTradeResponse)
	err := c.cc.Invoke(ctx, ManagementService_RegisterFilledTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateTradeStatus(ctx context.Context, in *UpdateTradeStatusRequest, opts ...grpc.CallOption) (*UpdateTradeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTradeStatusResponse)
	err := c.cc.Invoke(ctx, ManagementService_UpdateTradeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetManagedTrades(ctx context.Context, in *GetManagedTradesRequest, opts ...grpc.CallOption) (*GetManagedTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagedTradesResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetManagedTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetTradeJournal(ctx context.Context, in *GetTradeJournalRequest, opts ...grpc.CallOption) (*GetTradeJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradeJournalResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetTradeJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetPerformanceMetrics(ctx context.Context, in *GetPerformanceMetricsRequest, opts ...grpc.CallOption) (*GetPerformanceMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPerformanceMetricsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetPerformanceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetManualJournal(ctx context.Context, in *GetManualJournalRequest, opts ...grpc.CallOption) (*GetManualJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManualJournalResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetManualJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// ManagementService is the gRPC contract for Module C (Trade Management).
// The Gateway is the primary client. Module C implements this server.
// Triggered when a trade is FILLED at the broker (Step 7 of the architecture).
type ManagementServiceServer interface {
	// RegisterFilledTrade is called by the Gateway immediately after the
	// Execution service confirms an order is FILLED. This transfers full
	// ownership of the trade to Module C for lifecycle management:
	// break-even, trailing, partial closes, EOD protocols, and journaling.
	RegisterFilledTrade(context.Context, *RegisterFilledTradeRequest) (*RegisterFilledTradeResponse, error)
	// UpdateTradeStatus allows Module C to report TP/SL hits, partial
	// closes, and final closures back to the Gateway for orchestration
	// awareness and dashboard visibility.
	UpdateTradeStatus(context.Context, *UpdateTradeStatusRequest) (*UpdateTradeStatusResponse, error)
	// GetManagedTrades returns all trades currently under Module C management.
	GetManagedTrades(context.Context, *GetManagedTradesRequest) (*GetManagedTradesResponse, error)
	// GetTradeJournal returns closed trade history with full journal detail.
	GetTradeJournal(context.Context, *GetTradeJournalRequest) (*GetTradeJournalResponse, error)
	// GetPerformanceMetrics returns real-time analytics (win rate, expectancy, etc.).
	GetPerformanceMetrics(context.Context, *GetPerformanceMetricsRequest) (*GetPerformanceMetricsResponse, error)
	// GetHealth returns the management service's health status.
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// GetManualJournal returns the user's manually-executed / reconciled
	// trades (origin = MANUAL_RECONCILED) within a time window, BOTH open
	// and closed. It powers the 90-Day Trading Plan's Daily Execution
	// Journal auto-populate: the gateway composites these objective facts
	// with the trader's saved subjective annotations. System-executed
	// trades and rough MANUAL_RESTORED history rows are excluded.
	GetManualJournal(context.Context, *GetManualJournalRequest) (*GetManualJournalResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) RegisterFilledTrade(context.Context, *RegisterFilledTradeRequest) (*RegisterFilledTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFilledTrade not implemented")
}
func (UnimplementedManagementServiceServer) UpdateTradeStatus(context.Context, *UpdateTradeStatusRequest) (*UpdateTradeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTradeStatus not implemented")
}
func (UnimplementedManagementServiceServer) GetManagedTrades(context.Context, *GetManagedTradesRequest) (*GetManagedTradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManagedTrades not implemented")
}
func (UnimplementedManagementServiceServer) GetTradeJournal(context.Context, *GetTradeJournalRequest) (*GetTradeJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradeJournal not implemented")
}
func (UnimplementedManagementServiceServer) GetPerformanceMetrics(context.Context, *GetPerformanceMetricsRequest) (*GetPerformanceMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerformanceMetrics not implemented")
}
func (UnimplementedManagementServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedManagementServiceServer) GetManualJournal(context.Context, *GetManualJournalRequest) (*GetManualJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManualJournal not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_RegisterFilledTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFilledTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RegisterFilledTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RegisterFilledTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RegisterFilledTrade(ctx, req.(*RegisterFilledTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateTradeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateTradeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateTradeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateTradeStatus(ctx, req.(*UpdateTradeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetManagedTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagedTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetManagedTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetManagedTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetManagedTrades(ctx, req.(*GetManagedTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetTradeJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetTradeJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetTradeJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetTradeJournal(ctx, req.(*GetTradeJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetPerformanceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetPerformanceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetPerformanceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetPerformanceMetrics(ctx, req.(*GetPerformanceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetManualJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManualJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetManualJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetManualJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetManualJournal(ctx, req.(*GetManualJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "management.v1.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFilledTrade",
			Handler:    _ManagementService_RegisterFilledTrade_Handler,
		},
		{
			MethodName: "UpdateTradeStatus",
			Handler:    _ManagementService_UpdateTradeStatus_Handler,
		},
		{
			MethodName: "GetManagedTrades",
			Handler:    _ManagementService_GetManagedTrades_Handler,
		},
		{
			MethodName: "GetTradeJournal",
			Handler:    _ManagementService_GetTradeJournal_Handler,
		},
		{
			MethodName: "GetPerformanceMetrics",
			Handler:    _ManagementService_GetPerformanceMetrics_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ManagementService_GetHealth_Handler,
		},
		{
			MethodName: "GetManualJournal",
			Handler:    _ManagementService_GetManualJournal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/v1/management.proto",
}
