// Package tradingplan implements the Personalized 90-Day Trading
// Development Plan — the user-facing "HOW I OPERATE" workbook that
// complements the "HOW I TRADE" Trading System.
//
// PRACTICE.md anchors every design decision here:
//
//   - The Trading System (src/tradingsystem) is the engine's source
//     of truth for analysis and execution. It is NEVER exported.
//   - The Trading Plan (this package) is a structured trader workbook
//     generated by the platform LLM after the user completes the
//     Trading System builder. It is downloadable, printable,
//     Excel-exportable, manually fillable, and the engine NEVER
//     consumes it. Its sole purpose is human discipline, consistency,
//     and structured growth.
//
// Authority separation (must remain true):
//
//   Layer A — Trading System  : governs AI execution.
//   Layer B — Trading Plan    : governs human discipline (this pkg).
//
// The six sections below map 1:1 to PRACTICE.md's "Recommended 90-Day
// Plan Structure". They are intentionally typed and bounded so the
// LLM cannot drift the schema: the generator parses the LLM response
// into this struct and rejects anything that does not validate.
package tradingplan

import (
	"time"
)

// CurrentSchemaVersion is bumped any time a backwards-incompatible
// field is added or removed from Plan. The frontend persists the
// schema_version alongside every plan so a future migration knows
// which payloads need upgrading.
const CurrentSchemaVersion = 1

// ---------------------------------------------------------------------------
// Status — lifecycle of a user's plan
// ---------------------------------------------------------------------------

// Status is the lifecycle state of a user's trading plan.
//
//   StatusNone       — the user has not generated a plan yet (and
//                      may not have completed the Trading System).
//   StatusGenerating — the LLM call is in flight. The frontend polls
//                      and renders a friendly progress state.
//   StatusFailed     — the most recent generation attempt failed.
//                      The previous successful plan (if any) is
//                      preserved unchanged; the failure message is
//                      surfaced to the UI so the user can retry.
//   StatusActive     — a plan has been generated and is ready to use.
type Status string

const (
	StatusNone       Status = "none"
	StatusGenerating Status = "generating"
	StatusFailed     Status = "failed"
	StatusActive     Status = "active"
)

// IsValid reports whether the value is one of the recognised states.
func (s Status) IsValid() bool {
	switch s {
	case StatusNone, StatusGenerating, StatusFailed, StatusActive:
		return true
	}
	return false
}

// ---------------------------------------------------------------------------
// Section 1 — Trader Profile (generated narrative summary)
// ---------------------------------------------------------------------------

// TraderProfile is the AI-generated bullet summary the user reads at
// the top of the workbook. Free-form bullets so the LLM can capture
// the user's exact identity: style, conservatism, sessions, frequency,
// risk band, edge bias, news posture. Strict caps prevent the
// generator from running away — the workbook is meant to fit on a
// single printed page in this section.
type TraderProfile struct {
	Headline string   `json:"headline"` // one-liner, e.g. "Intraday momentum trader"
	Bullets  []string `json:"bullets"`  // 4..8 short factual bullets
}

// ---------------------------------------------------------------------------
// Section 2 — Account Parameters (table)
// ---------------------------------------------------------------------------

// AccountParameters is the second section: a small fixed-shape table
// the user can edit in-app and that prints cleanly to Excel. Every
// field is a string so the UI renders the AI-formatted value verbatim
// ("$50,000", "1%", "1:4") without lossy float -> string coercions.
//
// The shape is intentionally fixed (no map[string]string) so the
// frontend can render a stable header row and so future versions can
// add validation without a schema migration on existing rows.
type AccountParameters struct {
	StartingBalance    string `json:"starting_balance"`     // e.g. "$50,000"
	MaxDailyRisk       string `json:"max_daily_risk"`       // e.g. "1%"
	MaxWeeklyDrawdown  string `json:"max_weekly_drawdown"`  // e.g. "4%"
	PreferredRR        string `json:"preferred_rr"`         // e.g. "1:4"
	MaxTradesPerDay    string `json:"max_trades_per_day"`   // e.g. "2"
	TradingDaysPerWeek string `json:"trading_days_per_week"` // e.g. "5"
}

// ---------------------------------------------------------------------------
// Section 3 — Daily Execution Journal (the core operational table)
// ---------------------------------------------------------------------------

// JournalRow is one row of the Daily Execution Journal. The 25
// columns mirror PRACTICE.md's final specification exactly:
//
//   Date, Session, Pair, Direction, Style, SetupType, HTFBias,
//   Entry, StopLoss, TakeProfit, RiskPercent, PositionSize, Exit,
//   RRPlanned, RRAchieved, PnL, Outcome, RuleFollowed,
//   EmotionBeforeTrade, EmotionAfterTrade, TradeQuality,
//   MistakeCategory, NewsPresent, ScreenshotLink, Notes.
//
// Strings everywhere because the table is a manual journal — the
// user types whatever they want. The backend never math-evaluates
// these fields; the LLM seeds blank rows on initial generation and
// the user fills them in.
type JournalRow struct {
	Date               string `json:"date"`
	Session            string `json:"session"`
	Pair               string `json:"pair"`
	Direction          string `json:"direction"`
	Style              string `json:"style"`
	SetupType          string `json:"setup_type"`
	HTFBias            string `json:"htf_bias"`
	Entry              string `json:"entry"`
	StopLoss           string `json:"stop_loss"`
	TakeProfit         string `json:"take_profit"`
	RiskPercent        string `json:"risk_percent"`
	PositionSize       string `json:"position_size"`
	Exit               string `json:"exit"`
	RRPlanned          string `json:"rr_planned"`
	RRAchieved         string `json:"rr_achieved"`
	PnL                string `json:"pnl"`
	Outcome            string `json:"outcome"`
	RuleFollowed       string `json:"rule_followed"`
	EmotionBeforeTrade string `json:"emotion_before_trade"`
	EmotionAfterTrade  string `json:"emotion_after_trade"`
	TradeQuality       string `json:"trade_quality"`
	MistakeCategory    string `json:"mistake_category"`
	NewsPresent        string `json:"news_present"`
	ScreenshotLink     string `json:"screenshot_link"`
	Notes              string `json:"notes"`
}

// ---------------------------------------------------------------------------
// Section 4 — Weekly Review prompts
// ---------------------------------------------------------------------------

// WeeklyReview is the AI-generated list of self-reflection prompts
// the user answers at the end of every trading week. PRACTICE.md
// emphasises this is the section that turns the workbook from a
// log into a psychology tool.
type WeeklyReview struct {
	Prompts []string `json:"prompts"` // 5..10 self-reflection prompts
}

// ---------------------------------------------------------------------------
// Section 5 — Discipline Scorecard
// ---------------------------------------------------------------------------

// DisciplineScorecardItem is one row of the scorecard. Score is a
// string ("8/10") because the LLM seeds with empty values and the
// user fills manually; the frontend can later attach a numeric input
// without a schema migration.
type DisciplineScorecardItem struct {
	Metric string `json:"metric"`
	Score  string `json:"score"`
}

// DisciplineScorecard groups the items so a future version can add
// metadata (period covered, comments) without breaking the wire
// format.
type DisciplineScorecard struct {
	Items []DisciplineScorecardItem `json:"items"`
}

// ---------------------------------------------------------------------------
// Section 6 — 90-Day Objectives
// ---------------------------------------------------------------------------

// Objectives is the realistic-only behavioural goals list. The
// generator's system prompt explicitly forbids profit promises and
// compounding fantasies; the validator double-checks this at parse
// time so a model that ignores the prompt cannot persist a banned
// objective.
type Objectives struct {
	Items []string `json:"items"`
}

// ---------------------------------------------------------------------------
// Plan — the persisted six-section workbook
// ---------------------------------------------------------------------------

// Plan is the canonical six-section workbook. Persisted as JSONB and
// returned verbatim to the SPA. Adding a field requires bumping
// CurrentSchemaVersion so older clients can warn or upgrade.
type Plan struct {
	SchemaVersion int                 `json:"schema_version"`
	TraderProfile TraderProfile       `json:"trader_profile"`
	Account       AccountParameters   `json:"account"`
	Journal       []JournalRow        `json:"journal"`
	WeeklyReview  WeeklyReview        `json:"weekly_review"`
	Scorecard     DisciplineScorecard `json:"scorecard"`
	Objectives    Objectives          `json:"objectives"`

	// Footer fields ("Generated By Exoper AI" + metadata).
	//
	// PRACTICE.md requires every plan to carry generation_date,
	// trader_profile_summary, and version_id so the user (and a
	// future progression-analytics surface) can compare evolution
	// over time. Storing them on the plan itself rather than only
	// on the row keeps a downloaded Excel copy self-describing.
	GeneratedAt       time.Time `json:"generated_at"`
	GeneratedBy       string    `json:"generated_by"`        // "Exoper AI"
	ProfileSummary    string    `json:"profile_summary"`     // one-line snapshot
	ProfileVersion    int       `json:"profile_version"`     // trading-system version at gen time
	BalanceUsed       float64   `json:"balance_used"`        // numeric balance the LLM saw
	BalanceCurrency   string    `json:"balance_currency"`    // ISO 4217
	BalanceSourceKind string    `json:"balance_source_kind"` // "broker" | "fallback"

	// GenerationStartedAt is stamped by the engine at the moment the
	// LLM call is dispatched. The gateway uses it on callback to
	// record TradingPlanLLMCallDuration accurately. Optional on the
	// wire (older callbacks may omit it); when zero the metric is
	// skipped rather than reporting a misleading value derived from
	// row CreatedAt.
	GenerationStartedAt time.Time `json:"generation_started_at,omitempty"`
}

// ---------------------------------------------------------------------------
// Record — the persisted row
// ---------------------------------------------------------------------------

// Record is the gateway-side representation of one row in
// user_trading_plans. UserID is the primary key; we keep exactly
// one row per user and overwrite on regenerate.
//
// LastError is non-empty only when Status is StatusFailed; it carries
// a short user-facing message (no stack, no internal IDs) so the SPA
// can render a retry prompt.
type Record struct {
	UserID    string    `json:"user_id"`
	Status    Status    `json:"status"`
	Version   int       `json:"version"`
	Plan      *Plan     `json:"plan,omitempty"`
	LastError string    `json:"last_error,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// StatusView is the lightweight projection returned by the GET status
// endpoint. Same shape philosophy as tradingsystem.StatusView: an
// optional *time.Time so the JSON omits the field for users who
// have no row instead of emitting the Go zero value.
type StatusView struct {
	Status    Status     `json:"status"`
	Version   int        `json:"version"`
	HasPlan   bool       `json:"has_plan"`
	LastError string     `json:"last_error,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ---------------------------------------------------------------------------
// Generation inputs / outputs
// ---------------------------------------------------------------------------

// BalanceSource identifies where the account balance used by the
// generator came from. The frontend renders a small badge in the
// footer so users know whether their plan was anchored on a live
// broker number or the safe fallback.
type BalanceSource string

const (
	BalanceSourceBroker   BalanceSource = "broker"
	BalanceSourceFallback BalanceSource = "fallback"
)

// GenerationRequest is the typed input to the generator. Lives here
// (not in the engine) so both sides share the same field names and
// the gateway can JSON-marshal once.
type GenerationRequest struct {
	UserID          string        `json:"user_id"`
	Balance         float64       `json:"balance"`
	BalanceCurrency string        `json:"balance_currency"`
	BalanceSource   BalanceSource `json:"balance_source"`
	ProfileVersion  int           `json:"profile_version"`
	// Profile is the raw Trading-System profile. We deliberately
	// pass it as json.RawMessage at the wire layer (see the engine
	// caller) so the gateway does not need to import the
	// tradingsystem package types here.
	ProfileJSON []byte `json:"profile"`
}

// JournalSeedDays is the number of blank rows the LLM is asked to
// seed in Section 3 on initial generation. 90 days at 5 trading days
// per week = 64.28..; we round to 65 to keep the workbook printable
// on a single batch of pages while still spanning the 90-day window.
const JournalSeedDays = 65
