{{- if and .Values.tracing.enabled .Values.tracing.jaeger.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olog.jaeger.fullname" . }}
  namespace: {{ include "olog.namespace" . }}
  labels:
    {{- include "olog.jaeger.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}