{{- if and .Values.tracing.enabled .Values.tracing.collector.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "olog.collector.fullname" . }}
  namespace: {{ include "olog.namespace" . }}
  labels:
    {{- include "olog.collector.selectorLabels" . | nindent 4 }}
    {{- with .Values.tracing.collector.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "olog.collector.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "olog.namespace" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.tracing.collector.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.tracing.collector.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}