{{- if .Values.tracing.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olog.collector.fullname" . }}
  namespace: {{ include "olog.namespace" . }}
  labels:
    {{- include "olog.collector.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}