apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "olog.promtail.fullname" . }}
  labels:
    {{- include "olog.promtail.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "olog.promtail.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "olog.promtail.fullname" . }}
    namespace: {{ include "olog.namespace" . }}
