apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olog.loki.fullname" . }}
  namespace: {{ include "olog.namespace" . }}
  labels:
    {{- include "olog.loki.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olog.promtail.fullname" . }}
  namespace: {{ include "olog.namespace" . }}
  labels:
    {{- include "olog.promtail.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: true
