apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-system

commonLabels:
  app.kubernetes.io/name: etradie-envoy
  app.kubernetes.io/component: proxy
  app.kubernetes.io/part-of: etradie
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - configmap-wasm.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml

images:
  - name: envoyproxy/envoy
    newTag: v1.28-latest

replicas:
  - name: etradie-envoy
    count: 3
