apiVersion: apps/v1
kind: Deployment
metadata:
  name: exoper-envoy
  namespace: envoy-system
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    spec:
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 60
      containers:
        - name: envoy
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: "4"
              memory: 8Gi
              ephemeral-storage: 2Gi
          startupProbe:
            httpGet:
              path: /ready
              port: 9901
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 30
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/envoy
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 200Mi
            medium: Memory
        - name: cache
          emptyDir:
            sizeLimit: 1Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: exoper-envoy
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: exoper-envoy
---
apiVersion: v1
kind: LimitRange
metadata:
  name: envoy-limit-range
  namespace: envoy-system
spec:
  limits:
    - max:
        cpu: "4"
        memory: 8Gi
        ephemeral-storage: 2Gi
      min:
        cpu: "2"
        memory: 4Gi
        ephemeral-storage: 1Gi
      default:
        cpu: "4"
        memory: 8Gi
        ephemeral-storage: 2Gi
      defaultRequest:
        cpu: "2"
        memory: 4Gi
        ephemeral-storage: 1Gi
      type: Container
