{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edge-ingress.fullname" . }}
  namespace: {{ include "edge-ingress.namespace" . }}
  labels:
    {{- include "edge-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: availability
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "edge-ingress.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy | default "AlwaysAllow" }}
{{- end }}
