// TypeScript mirror of src/tradingplan/models.go. Keep field names
// in lockstep with the Go source of truth; any drift here is a typed
// bug the SPA build catches before runtime.
//
// Schema:
//   - Section 1 — Trader Profile (narrative bullet summary)
//   - Section 2 — Account Parameters (table)
//   - Section 3 — Daily Execution Journal (the core table)
//   - Section 4 — Weekly Review (reflection prompts)
//   - Section 5 — Discipline Scorecard (metric/score)
//   - Section 6 — 90-Day Objectives
//
// Footer fields ("Generated By Exoper AI") carry generation metadata
// the workbook displays at the bottom.

export type TradingPlanStatus = 'none' | 'generating' | 'failed' | 'active';
export type BalanceSourceKind = 'broker' | 'fallback';

// -- Section 1 --------------------------------------------------------------
export interface TraderProfile {
  headline: string;
  bullets: string[];
}

// -- Section 2 --------------------------------------------------------------
export interface AccountParameters {
  starting_balance: string;
  max_daily_risk: string;
  max_weekly_drawdown: string;
  preferred_rr: string;
  max_trades_per_day: string;
  trading_days_per_week: string;
}

// -- Section 3 --------------------------------------------------------------
// 25-column Daily Execution Journal. Field names lockstep with
// src/tradingplan/models.go::JournalRow.
export interface JournalRow {
  date: string;
  session: string;
  pair: string;
  direction: string;
  style: string;
  setup_type: string;
  htf_bias: string;
  entry: string;
  stop_loss: string;
  take_profit: string;
  risk_percent: string;
  position_size: string;
  exit: string;
  rr_planned: string;
  rr_achieved: string;
  pnl: string;
  outcome: string;
  rule_followed: string;
  emotion_before_trade: string;
  emotion_after_trade: string;
  trade_quality: string;
  mistake_category: string;
  news_present: string;
  screenshot_link: string;
  notes: string;
}

// -- Section 3b -------------------------------------------------------------
// JournalAnnotation holds ONLY the trader's subjective journal columns
// for one manually-executed / reconciled trade, keyed by the management
// trade_id. Lockstep with src/tradingplan/models.go::JournalAnnotation.
// The objective columns are composited live from the management service
// in the journal view and are never stored here.
export interface JournalAnnotation {
  trade_id: string;
  htf_bias: string;
  rule_followed: string;
  emotion_before_trade: string;
  emotion_after_trade: string;
  trade_quality: string;
  mistake_category: string;
  news_present: string;
  screenshot_link: string;
  notes: string;
}

// CompositeJournalRow is one Daily-Execution-Journal row as served by
// GET /api/v1/trading-plan/journal: the OBJECTIVE cells (read-only,
// deterministically formatted by the gateway from the management
// manual-trade record) joined with the trader's SUBJECTIVE cells (from
// the saved annotation). Lockstep with tradingplan.CompositeJournalRow.
// is_open => the close cells (exit / rr_achieved / pnl / outcome) are
// blank and the trade is still live.
export interface CompositeJournalRow {
  trade_id: string;
  is_open: boolean;

  // Objective (read-only, formatted by the gateway per design §7).
  date: string;
  session: string;
  pair: string;
  direction: string;
  style: string;
  setup_type: string;
  entry: string;
  stop_loss: string;
  take_profit: string;
  risk_percent: string;
  position_size: string;
  exit: string;
  rr_planned: string;
  rr_achieved: string;
  pnl: string;
  outcome: string;

  // Subjective (editable, from the saved annotation).
  htf_bias: string;
  rule_followed: string;
  emotion_before_trade: string;
  emotion_after_trade: string;
  trade_quality: string;
  mistake_category: string;
  news_present: string;
  screenshot_link: string;
  notes: string;
}

// JournalWindow selects which 90-day window the composite view shows.
// 'current' is the most recent 90 days; 'previous' is the 90 days
// before that (the UI pages back without ever losing a trade).
export type JournalWindow = 'current' | 'previous';

// JournalView is the GET /api/v1/trading-plan/journal response. rows are
// ordered newest-first (open trades first, then closed within the
// window); total_closed is the count of closed manual trades in the
// window for the paging affordance; window_days is the window span (90).
export interface JournalView {
  window: JournalWindow;
  rows: CompositeJournalRow[];
  total_closed: number;
  window_days: number;
}

// -- Section 4 --------------------------------------------------------------
export interface WeeklyReview {
  prompts: string[];
}

// -- Section 5 --------------------------------------------------------------
export interface DisciplineScorecardItem {
  metric: string;
  score: string;
}
export interface DisciplineScorecard {
  items: DisciplineScorecardItem[];
}

// -- Section 6 --------------------------------------------------------------
export interface Objectives {
  items: string[];
}

// -- Full plan ---------------------------------------------------------------
export interface TradingPlan {
  schema_version: number;
  trader_profile: TraderProfile;
  account: AccountParameters;
  journal: JournalRow[];
  // Subjective annotations for auto-populated manual trades, keyed by
  // management trade_id (schema v2). The objective columns are
  // composited live from management in the journal view; only these
  // annotations persist in the plan. Optional on the wire so a v1 plan
  // (no annotations yet) still type-checks.
  journal_annotations?: JournalAnnotation[];
  weekly_review: WeeklyReview;
  scorecard: DisciplineScorecard;
  objectives: Objectives;

  // Footer / metadata
  generated_at: string; // ISO 8601
  generated_by: string; // "Exoper AI"
  profile_summary: string;
  profile_version: number;
  balance_used: number;
  balance_currency: string;
  balance_source_kind: BalanceSourceKind;
}

// Full GET response (/api/v1/trading-plan).
export interface TradingPlanRecord {
  status: TradingPlanStatus;
  version: number;
  plan: TradingPlan | null;
  has_plan: boolean;
  last_error?: string;
  created_at?: string;
  updated_at?: string;
}

// Lightweight projection (/api/v1/trading-plan/status).
export interface TradingPlanStatusView {
  status: TradingPlanStatus;
  version: number;
  has_plan: boolean;
  last_error?: string;
  updated_at?: string;
}

// 422 envelope from the gateway.
export class TradingPlanValidationError extends Error {
  public readonly fields: Record<string, string>;
  constructor(message: string, fields: Record<string, string>) {
    super(message);
    this.name = 'TradingPlanValidationError';
    this.fields = fields;
  }
}

// Body shape for POST /generate. Both fields optional — if omitted
// (or zero), the gateway uses the live broker balance with a $10,000
// USD fallback when the broker is unavailable.
export interface GenerateOptions {
  fallback_balance?: number;
  fallback_currency?: string;
}
