// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: engine/v1/engine.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalyzeTA messages.
type AnalyzeTARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTARequest) Reset() {
	*x = AnalyzeTARequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTARequest) ProtoMessage() {}

func (x *AnalyzeTARequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTARequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTARequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeTARequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AnalyzeTARequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type TASymbolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	HtfTimeframes []string               `protobuf:"bytes,2,rep,name=htf_timeframes,json=htfTimeframes,proto3" json:"htf_timeframes,omitempty"`
	LtfTimeframes []string               `protobuf:"bytes,3,rep,name=ltf_timeframes,json=ltfTimeframes,proto3" json:"ltf_timeframes,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Candidates and snapshots are JSON-encoded for flexibility.
	SmcCandidatesJson []byte `protobuf:"bytes,5,opt,name=smc_candidates_json,json=smcCandidatesJson,proto3" json:"smc_candidates_json,omitempty"`
	SndCandidatesJson []byte `protobuf:"bytes,6,opt,name=snd_candidates_json,json=sndCandidatesJson,proto3" json:"snd_candidates_json,omitempty"`
	SnapshotsJson     []byte `protobuf:"bytes,7,opt,name=snapshots_json,json=snapshotsJson,proto3" json:"snapshots_json,omitempty"`
	AlignmentJson     []byte `protobuf:"bytes,8,opt,name=alignment_json,json=alignmentJson,proto3" json:"alignment_json,omitempty"`
	OverallTrend      string `protobuf:"bytes,9,opt,name=overall_trend,json=overallTrend,proto3" json:"overall_trend,omitempty"`
	Error             string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TASymbolResult) Reset() {
	*x = TASymbolResult{}
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TASymbolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TASymbolResult) ProtoMessage() {}

func (x *TASymbolResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TASymbolResult.ProtoReflect.Descriptor instead.
func (*TASymbolResult) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *TASymbolResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TASymbolResult) GetHtfTimeframes() []string {
	if x != nil {
		return x.HtfTimeframes
	}
	return nil
}

func (x *TASymbolResult) GetLtfTimeframes() []string {
	if x != nil {
		return x.LtfTimeframes
	}
	return nil
}

func (x *TASymbolResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TASymbolResult) GetSmcCandidatesJson() []byte {
	if x != nil {
		return x.SmcCandidatesJson
	}
	return nil
}

func (x *TASymbolResult) GetSndCandidatesJson() []byte {
	if x != nil {
		return x.SndCandidatesJson
	}
	return nil
}

func (x *TASymbolResult) GetSnapshotsJson() []byte {
	if x != nil {
		return x.SnapshotsJson
	}
	return nil
}

func (x *TASymbolResult) GetAlignmentJson() []byte {
	if x != nil {
		return x.AlignmentJson
	}
	return nil
}

func (x *TASymbolResult) GetOverallTrend() string {
	if x != nil {
		return x.OverallTrend
	}
	return ""
}

func (x *TASymbolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AnalyzeTAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolResults []*TASymbolResult      `protobuf:"bytes,1,rep,name=symbol_results,json=symbolResults,proto3" json:"symbol_results,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTAResponse) Reset() {
	*x = AnalyzeTAResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTAResponse) ProtoMessage() {}

func (x *AnalyzeTAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTAResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTAResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeTAResponse) GetSymbolResults() []*TASymbolResult {
	if x != nil {
		return x.SymbolResults
	}
	return nil
}

func (x *AnalyzeTAResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// CollectMacro messages.
type CollectMacroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectMacroRequest) Reset() {
	*x = CollectMacroRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectMacroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectMacroRequest) ProtoMessage() {}

func (x *CollectMacroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectMacroRequest.ProtoReflect.Descriptor instead.
func (*CollectMacroRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{3}
}

func (x *CollectMacroRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CollectMacroResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each dataset is JSON-encoded; nil means the collector failed or had no data.
	CentralBankJson []byte            `protobuf:"bytes,1,opt,name=central_bank_json,json=centralBankJson,proto3" json:"central_bank_json,omitempty"`
	CotJson         []byte            `protobuf:"bytes,2,opt,name=cot_json,json=cotJson,proto3" json:"cot_json,omitempty"`
	EconomicJson    []byte            `protobuf:"bytes,3,opt,name=economic_json,json=economicJson,proto3" json:"economic_json,omitempty"`
	NewsJson        []byte            `protobuf:"bytes,4,opt,name=news_json,json=newsJson,proto3" json:"news_json,omitempty"`
	CalendarJson    []byte            `protobuf:"bytes,5,opt,name=calendar_json,json=calendarJson,proto3" json:"calendar_json,omitempty"`
	DxyJson         []byte            `protobuf:"bytes,6,opt,name=dxy_json,json=dxyJson,proto3" json:"dxy_json,omitempty"`
	IntermarketJson []byte            `protobuf:"bytes,7,opt,name=intermarket_json,json=intermarketJson,proto3" json:"intermarket_json,omitempty"`
	SentimentJson   []byte            `protobuf:"bytes,8,opt,name=sentiment_json,json=sentimentJson,proto3" json:"sentiment_json,omitempty"`
	DurationMs      float64           `protobuf:"fixed64,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Errors          map[string]string `protobuf:"bytes,10,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectMacroResponse) Reset() {
	*x = CollectMacroResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectMacroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectMacroResponse) ProtoMessage() {}

func (x *CollectMacroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectMacroResponse.ProtoReflect.Descriptor instead.
func (*CollectMacroResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *CollectMacroResponse) GetCentralBankJson() []byte {
	if x != nil {
		return x.CentralBankJson
	}
	return nil
}

func (x *CollectMacroResponse) GetCotJson() []byte {
	if x != nil {
		return x.CotJson
	}
	return nil
}

func (x *CollectMacroResponse) GetEconomicJson() []byte {
	if x != nil {
		return x.EconomicJson
	}
	return nil
}

func (x *CollectMacroResponse) GetNewsJson() []byte {
	if x != nil {
		return x.NewsJson
	}
	return nil
}

func (x *CollectMacroResponse) GetCalendarJson() []byte {
	if x != nil {
		return x.CalendarJson
	}
	return nil
}

func (x *CollectMacroResponse) GetDxyJson() []byte {
	if x != nil {
		return x.DxyJson
	}
	return nil
}

func (x *CollectMacroResponse) GetIntermarketJson() []byte {
	if x != nil {
		return x.IntermarketJson
	}
	return nil
}

func (x *CollectMacroResponse) GetSentimentJson() []byte {
	if x != nil {
		return x.SentimentJson
	}
	return nil
}

func (x *CollectMacroResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CollectMacroResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// RetrieveRAG messages.
type RetrieveRAGRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueryText          string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	Strategy           string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Framework          string                 `protobuf:"bytes,3,opt,name=framework,proto3" json:"framework,omitempty"`
	SetupFamily        string                 `protobuf:"bytes,4,opt,name=setup_family,json=setupFamily,proto3" json:"setup_family,omitempty"`
	Direction          string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Timeframe          string                 `protobuf:"bytes,6,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Style              string                 `protobuf:"bytes,7,opt,name=style,proto3" json:"style,omitempty"`
	Symbol             string                 `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AllFrameworks      []string               `protobuf:"bytes,9,rep,name=all_frameworks,json=allFrameworks,proto3" json:"all_frameworks,omitempty"`
	AllSetupFamilies   []string               `protobuf:"bytes,10,rep,name=all_setup_families,json=allSetupFamilies,proto3" json:"all_setup_families,omitempty"`
	HasSmcCandidates   bool                   `protobuf:"varint,11,opt,name=has_smc_candidates,json=hasSmcCandidates,proto3" json:"has_smc_candidates,omitempty"`
	HasSndCandidates   bool                   `protobuf:"varint,12,opt,name=has_snd_candidates,json=hasSndCandidates,proto3" json:"has_snd_candidates,omitempty"`
	HasMacroData       bool                   `protobuf:"varint,13,opt,name=has_macro_data,json=hasMacroData,proto3" json:"has_macro_data,omitempty"`
	HasCotData         bool                   `protobuf:"varint,14,opt,name=has_cot_data,json=hasCotData,proto3" json:"has_cot_data,omitempty"`
	HasRateDecision    bool                   `protobuf:"varint,15,opt,name=has_rate_decision,json=hasRateDecision,proto3" json:"has_rate_decision,omitempty"`
	HasHighImpactEvent bool                   `protobuf:"varint,16,opt,name=has_high_impact_event,json=hasHighImpactEvent,proto3" json:"has_high_impact_event,omitempty"`
	HasDxyData         bool                   `protobuf:"varint,17,opt,name=has_dxy_data,json=hasDxyData,proto3" json:"has_dxy_data,omitempty"`
	TraceId            string                 `protobuf:"bytes,18,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RetrieveRAGRequest) Reset() {
	*x = RetrieveRAGRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRAGRequest) ProtoMessage() {}

func (x *RetrieveRAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRAGRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRAGRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveRAGRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RetrieveRAGRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RetrieveRAGRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *RetrieveRAGRequest) GetSetupFamily() string {
	if x != nil {
		return x.SetupFamily
	}
	return ""
}

func (x *RetrieveRAGRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RetrieveRAGRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *RetrieveRAGRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *RetrieveRAGRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RetrieveRAGRequest) GetAllFrameworks() []string {
	if x != nil {
		return x.AllFrameworks
	}
	return nil
}

func (x *RetrieveRAGRequest) GetAllSetupFamilies() []string {
	if x != nil {
		return x.AllSetupFamilies
	}
	return nil
}

func (x *RetrieveRAGRequest) GetHasSmcCandidates() bool {
	if x != nil {
		return x.HasSmcCandidates
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasSndCandidates() bool {
	if x != nil {
		return x.HasSndCandidates
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasMacroData() bool {
	if x != nil {
		return x.HasMacroData
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasCotData() bool {
	if x != nil {
		return x.HasCotData
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasRateDecision() bool {
	if x != nil {
		return x.HasRateDecision
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasHighImpactEvent() bool {
	if x != nil {
		return x.HasHighImpactEvent
	}
	return false
}

func (x *RetrieveRAGRequest) GetHasDxyData() bool {
	if x != nil {
		return x.HasDxyData
	}
	return false
}

func (x *RetrieveRAGRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type RetrieveRAGResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full context bundle as JSON for maximum flexibility.
	ContextBundleJson []byte `protobuf:"bytes,1,opt,name=context_bundle_json,json=contextBundleJson,proto3" json:"context_bundle_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetrieveRAGResponse) Reset() {
	*x = RetrieveRAGResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRAGResponse) ProtoMessage() {}

func (x *RetrieveRAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRAGResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRAGResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveRAGResponse) GetContextBundleJson() []byte {
	if x != nil {
		return x.ContextBundleJson
	}
	return nil
}

// ProcessLLM messages.
type ProcessLLMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full processor input as JSON.
	ProcessorInputJson []byte `protobuf:"bytes,1,opt,name=processor_input_json,json=processorInputJson,proto3" json:"processor_input_json,omitempty"`
	TraceId            string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessLLMRequest) Reset() {
	*x = ProcessLLMRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessLLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLLMRequest) ProtoMessage() {}

func (x *ProcessLLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLLMRequest.ProtoReflect.Descriptor instead.
func (*ProcessLLMRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessLLMRequest) GetProcessorInputJson() []byte {
	if x != nil {
		return x.ProcessorInputJson
	}
	return nil
}

func (x *ProcessLLMRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ProcessLLMResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TradeValid      bool                   `protobuf:"varint,1,opt,name=trade_valid,json=tradeValid,proto3" json:"trade_valid,omitempty"`
	Direction       string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Symbol          string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Confidence      float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Grade           string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"`
	RiskPercentage  float64                `protobuf:"fixed64,6,opt,name=risk_percentage,json=riskPercentage,proto3" json:"risk_percentage,omitempty"`
	Reasoning       string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	EntryPrice      float64                `protobuf:"fixed64,8,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	StopLoss        float64                `protobuf:"fixed64,9,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfit      float64                `protobuf:"fixed64,10,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	RejectionRules  []string               `protobuf:"bytes,11,rep,name=rejection_rules,json=rejectionRules,proto3" json:"rejection_rules,omitempty"`
	RawResponseJson []byte                 `protobuf:"bytes,12,opt,name=raw_response_json,json=rawResponseJson,proto3" json:"raw_response_json,omitempty"`
	// Execution-critical fields for Module B.
	// entry_price above is the midpoint (kept for backward compat);
	// these provide the actual zone boundaries for limit order placement.
	EntryZoneLow  float64 `protobuf:"fixed64,13,opt,name=entry_zone_low,json=entryZoneLow,proto3" json:"entry_zone_low,omitempty"`
	EntryZoneHigh float64 `protobuf:"fixed64,14,opt,name=entry_zone_high,json=entryZoneHigh,proto3" json:"entry_zone_high,omitempty"`
	// All three TP levels with position sizing percentages.
	// Module B needs these for partial close management.
	Tp1Price float64 `protobuf:"fixed64,15,opt,name=tp1_price,json=tp1Price,proto3" json:"tp1_price,omitempty"`
	Tp1Pct   int32   `protobuf:"varint,16,opt,name=tp1_pct,json=tp1Pct,proto3" json:"tp1_pct,omitempty"`
	Tp2Price float64 `protobuf:"fixed64,17,opt,name=tp2_price,json=tp2Price,proto3" json:"tp2_price,omitempty"`
	Tp2Pct   int32   `protobuf:"varint,18,opt,name=tp2_pct,json=tp2Pct,proto3" json:"tp2_pct,omitempty"`
	Tp3Price float64 `protobuf:"fixed64,19,opt,name=tp3_price,json=tp3Price,proto3" json:"tp3_price,omitempty"`
	Tp3Pct   int32   `protobuf:"varint,20,opt,name=tp3_pct,json=tp3Pct,proto3" json:"tp3_pct,omitempty"`
	// Context required by Module B's pre-execution validator.
	TradingStyle    string  `protobuf:"bytes,21,opt,name=trading_style,json=tradingStyle,proto3" json:"trading_style,omitempty"`
	Session         string  `protobuf:"bytes,22,opt,name=session,proto3" json:"session,omitempty"`
	RrRatio         float64 `protobuf:"fixed64,23,opt,name=rr_ratio,json=rrRatio,proto3" json:"rr_ratio,omitempty"`
	ConfluenceScore float64 `protobuf:"fixed64,24,opt,name=confluence_score,json=confluenceScore,proto3" json:"confluence_score,omitempty"`
	AnalysisId      string  `protobuf:"bytes,25,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessLLMResponse) Reset() {
	*x = ProcessLLMResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLLMResponse) ProtoMessage() {}

func (x *ProcessLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLLMResponse.ProtoReflect.Descriptor instead.
func (*ProcessLLMResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessLLMResponse) GetTradeValid() bool {
	if x != nil {
		return x.TradeValid
	}
	return false
}

func (x *ProcessLLMResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ProcessLLMResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ProcessLLMResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ProcessLLMResponse) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *ProcessLLMResponse) GetRiskPercentage() float64 {
	if x != nil {
		return x.RiskPercentage
	}
	return 0
}

func (x *ProcessLLMResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ProcessLLMResponse) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *ProcessLLMResponse) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *ProcessLLMResponse) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *ProcessLLMResponse) GetRejectionRules() []string {
	if x != nil {
		return x.RejectionRules
	}
	return nil
}

func (x *ProcessLLMResponse) GetRawResponseJson() []byte {
	if x != nil {
		return x.RawResponseJson
	}
	return nil
}

func (x *ProcessLLMResponse) GetEntryZoneLow() float64 {
	if x != nil {
		return x.EntryZoneLow
	}
	return 0
}

func (x *ProcessLLMResponse) GetEntryZoneHigh() float64 {
	if x != nil {
		return x.EntryZoneHigh
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp1Price() float64 {
	if x != nil {
		return x.Tp1Price
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp1Pct() int32 {
	if x != nil {
		return x.Tp1Pct
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp2Price() float64 {
	if x != nil {
		return x.Tp2Price
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp2Pct() int32 {
	if x != nil {
		return x.Tp2Pct
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp3Price() float64 {
	if x != nil {
		return x.Tp3Price
	}
	return 0
}

func (x *ProcessLLMResponse) GetTp3Pct() int32 {
	if x != nil {
		return x.Tp3Pct
	}
	return 0
}

func (x *ProcessLLMResponse) GetTradingStyle() string {
	if x != nil {
		return x.TradingStyle
	}
	return ""
}

func (x *ProcessLLMResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ProcessLLMResponse) GetRrRatio() float64 {
	if x != nil {
		return x.RrRatio
	}
	return 0
}

func (x *ProcessLLMResponse) GetConfluenceScore() float64 {
	if x != nil {
		return x.ConfluenceScore
	}
	return 0
}

func (x *ProcessLLMResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

var File_engine_v1_engine_proto protoreflect.FileDescriptor

const file_engine_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x16engine/v1/engine.proto\x12\tengine.v1\"G\n" +
	"\x10AnalyzeTARequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\xf7\x02\n" +
	"\x0eTASymbolResult\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x0ehtf_timeframes\x18\x02 \x03(\tR\rhtfTimeframes\x12%\n" +
	"\x0eltf_timeframes\x18\x03 \x03(\tR\rltfTimeframes\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12.\n" +
	"\x13smc_candidates_json\x18\x05 \x01(\fR\x11smcCandidatesJson\x12.\n" +
	"\x13snd_candidates_json\x18\x06 \x01(\fR\x11sndCandidatesJson\x12%\n" +
	"\x0esnapshots_json\x18\a \x01(\fR\rsnapshotsJson\x12%\n" +
	"\x0ealignment_json\x18\b \x01(\fR\ralignmentJson\x12#\n" +
	"\roverall_trend\x18\t \x01(\tR\foverallTrend\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"v\n" +
	"\x11AnalyzeTAResponse\x12@\n" +
	"\x0esymbol_results\x18\x01 \x03(\v2\x19.engine.v1.TASymbolResultR\rsymbolResults\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x01R\n" +
	"durationMs\"0\n" +
	"\x13CollectMacroRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"\xd2\x03\n" +
	"\x14CollectMacroResponse\x12*\n" +
	"\x11central_bank_json\x18\x01 \x01(\fR\x0fcentralBankJson\x12\x19\n" +
	"\bcot_json\x18\x02 \x01(\fR\acotJson\x12#\n" +
	"\reconomic_json\x18\x03 \x01(\fR\feconomicJson\x12\x1b\n" +
	"\tnews_json\x18\x04 \x01(\fR\bnewsJson\x12#\n" +
	"\rcalendar_json\x18\x05 \x01(\fR\fcalendarJson\x12\x19\n" +
	"\bdxy_json\x18\x06 \x01(\fR\adxyJson\x12)\n" +
	"\x10intermarket_json\x18\a \x01(\fR\x0fintermarketJson\x12%\n" +
	"\x0esentiment_json\x18\b \x01(\fR\rsentimentJson\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x01R\n" +
	"durationMs\x12C\n" +
	"\x06errors\x18\n" +
	" \x03(\v2+.engine.v1.CollectMacroResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x05\n" +
	"\x12RetrieveRAGRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x1c\n" +
	"\tframework\x18\x03 \x01(\tR\tframework\x12!\n" +
	"\fsetup_family\x18\x04 \x01(\tR\vsetupFamily\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12\x1c\n" +
	"\ttimeframe\x18\x06 \x01(\tR\ttimeframe\x12\x14\n" +
	"\x05style\x18\a \x01(\tR\x05style\x12\x16\n" +
	"\x06symbol\x18\b \x01(\tR\x06symbol\x12%\n" +
	"\x0eall_frameworks\x18\t \x03(\tR\rallFrameworks\x12,\n" +
	"\x12all_setup_families\x18\n" +
	" \x03(\tR\x10allSetupFamilies\x12,\n" +
	"\x12has_smc_candidates\x18\v \x01(\bR\x10hasSmcCandidates\x12,\n" +
	"\x12has_snd_candidates\x18\f \x01(\bR\x10hasSndCandidates\x12$\n" +
	"\x0ehas_macro_data\x18\r \x01(\bR\fhasMacroData\x12 \n" +
	"\fhas_cot_data\x18\x0e \x01(\bR\n" +
	"hasCotData\x12*\n" +
	"\x11has_rate_decision\x18\x0f \x01(\bR\x0fhasRateDecision\x121\n" +
	"\x15has_high_impact_event\x18\x10 \x01(\bR\x12hasHighImpactEvent\x12 \n" +
	"\fhas_dxy_data\x18\x11 \x01(\bR\n" +
	"hasDxyData\x12\x19\n" +
	"\btrace_id\x18\x12 \x01(\tR\atraceId\"E\n" +
	"\x13RetrieveRAGResponse\x12.\n" +
	"\x13context_bundle_json\x18\x01 \x01(\fR\x11contextBundleJson\"`\n" +
	"\x11ProcessLLMRequest\x120\n" +
	"\x14processor_input_json\x18\x01 \x01(\fR\x12processorInputJson\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\xb2\x06\n" +
	"\x12ProcessLLMResponse\x12\x1f\n" +
	"\vtrade_valid\x18\x01 \x01(\bR\n" +
	"tradeValid\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\x12'\n" +
	"\x0frisk_percentage\x18\x06 \x01(\x01R\x0eriskPercentage\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12\x1f\n" +
	"\ventry_price\x18\b \x01(\x01R\n" +
	"entryPrice\x12\x1b\n" +
	"\tstop_loss\x18\t \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\n" +
	" \x01(\x01R\n" +
	"takeProfit\x12'\n" +
	"\x0frejection_rules\x18\v \x03(\tR\x0erejectionRules\x12*\n" +
	"\x11raw_response_json\x18\f \x01(\fR\x0frawResponseJson\x12$\n" +
	"\x0eentry_zone_low\x18\r \x01(\x01R\fentryZoneLow\x12&\n" +
	"\x0fentry_zone_high\x18\x0e \x01(\x01R\rentryZoneHigh\x12\x1b\n" +
	"\ttp1_price\x18\x0f \x01(\x01R\btp1Price\x12\x17\n" +
	"\atp1_pct\x18\x10 \x01(\x05R\x06tp1Pct\x12\x1b\n" +
	"\ttp2_price\x18\x11 \x01(\x01R\btp2Price\x12\x17\n" +
	"\atp2_pct\x18\x12 \x01(\x05R\x06tp2Pct\x12\x1b\n" +
	"\ttp3_price\x18\x13 \x01(\x01R\btp3Price\x12\x17\n" +
	"\atp3_pct\x18\x14 \x01(\x05R\x06tp3Pct\x12#\n" +
	"\rtrading_style\x18\x15 \x01(\tR\ftradingStyle\x12\x18\n" +
	"\asession\x18\x16 \x01(\tR\asession\x12\x19\n" +
	"\brr_ratio\x18\x17 \x01(\x01R\arrRatio\x12)\n" +
	"\x10confluence_score\x18\x18 \x01(\x01R\x0fconfluenceScore\x12\x1f\n" +
	"\vanalysis_id\x18\x19 \x01(\tR\n" +
	"analysisId2\xc1\x02\n" +
	"\rEngineService\x12F\n" +
	"\tAnalyzeTA\x12\x1b.engine.v1.AnalyzeTARequest\x1a\x1c.engine.v1.AnalyzeTAResponse\x12O\n" +
	"\fCollectMacro\x12\x1e.engine.v1.CollectMacroRequest\x1a\x1f.engine.v1.CollectMacroResponse\x12L\n" +
	"\vRetrieveRAG\x12\x1d.engine.v1.RetrieveRAGRequest\x1a\x1e.engine.v1.RetrieveRAGResponse\x12I\n" +
	"\n" +
	"ProcessLLM\x12\x1c.engine.v1.ProcessLLMRequest\x1a\x1d.engine.v1.ProcessLLMResponseB8Z6github.com/flamegreat/etradie/proto/engine/v1;enginev1b\x06proto3"

var (
	file_engine_v1_engine_proto_rawDescOnce sync.Once
	file_engine_v1_engine_proto_rawDescData []byte
)

func file_engine_v1_engine_proto_rawDescGZIP() []byte {
	file_engine_v1_engine_proto_rawDescOnce.Do(func() {
		file_engine_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)))
	})
	return file_engine_v1_engine_proto_rawDescData
}

var file_engine_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_engine_v1_engine_proto_goTypes = []any{
	(*AnalyzeTARequest)(nil),     // 0: engine.v1.AnalyzeTARequest
	(*TASymbolResult)(nil),       // 1: engine.v1.TASymbolResult
	(*AnalyzeTAResponse)(nil),    // 2: engine.v1.AnalyzeTAResponse
	(*CollectMacroRequest)(nil),  // 3: engine.v1.CollectMacroRequest
	(*CollectMacroResponse)(nil), // 4: engine.v1.CollectMacroResponse
	(*RetrieveRAGRequest)(nil),   // 5: engine.v1.RetrieveRAGRequest
	(*RetrieveRAGResponse)(nil),  // 6: engine.v1.RetrieveRAGResponse
	(*ProcessLLMRequest)(nil),    // 7: engine.v1.ProcessLLMRequest
	(*ProcessLLMResponse)(nil),   // 8: engine.v1.ProcessLLMResponse
	nil,                          // 9: engine.v1.CollectMacroResponse.ErrorsEntry
}
var file_engine_v1_engine_proto_depIdxs = []int32{
	1, // 0: engine.v1.AnalyzeTAResponse.symbol_results:type_name -> engine.v1.TASymbolResult
	9, // 1: engine.v1.CollectMacroResponse.errors:type_name -> engine.v1.CollectMacroResponse.ErrorsEntry
	0, // 2: engine.v1.EngineService.AnalyzeTA:input_type -> engine.v1.AnalyzeTARequest
	3, // 3: engine.v1.EngineService.CollectMacro:input_type -> engine.v1.CollectMacroRequest
	5, // 4: engine.v1.EngineService.RetrieveRAG:input_type -> engine.v1.RetrieveRAGRequest
	7, // 5: engine.v1.EngineService.ProcessLLM:input_type -> engine.v1.ProcessLLMRequest
	2, // 6: engine.v1.EngineService.AnalyzeTA:output_type -> engine.v1.AnalyzeTAResponse
	4, // 7: engine.v1.EngineService.CollectMacro:output_type -> engine.v1.CollectMacroResponse
	6, // 8: engine.v1.EngineService.RetrieveRAG:output_type -> engine.v1.RetrieveRAGResponse
	8, // 9: engine.v1.EngineService.ProcessLLM:output_type -> engine.v1.ProcessLLMResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engine_v1_engine_proto_init() }
func file_engine_v1_engine_proto_init() {
	if File_engine_v1_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_v1_engine_proto_goTypes,
		DependencyIndexes: file_engine_v1_engine_proto_depIdxs,
		MessageInfos:      file_engine_v1_engine_proto_msgTypes,
	}.Build()
	File_engine_v1_engine_proto = out.File
	file_engine_v1_engine_proto_goTypes = nil
	file_engine_v1_engine_proto_depIdxs = nil
}
