// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: engine/v1/engine.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_AnalyzeTA_FullMethodName    = "/engine.v1.EngineService/AnalyzeTA"
	EngineService_CollectMacro_FullMethodName = "/engine.v1.EngineService/CollectMacro"
	EngineService_RetrieveRAG_FullMethodName  = "/engine.v1.EngineService/RetrieveRAG"
	EngineService_ProcessLLM_FullMethodName   = "/engine.v1.EngineService/ProcessLLM"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineService is the gRPC contract between the Go gateway and the
// Python engine (Module A). The Python engine implements this server;
// the Go gateway is the client.
type EngineServiceClient interface {
	// AnalyzeTA runs technical analysis for the given symbols.
	AnalyzeTA(ctx context.Context, in *AnalyzeTARequest, opts ...grpc.CallOption) (*AnalyzeTAResponse, error)
	// CollectMacro runs all 8 macro collectors in parallel.
	CollectMacro(ctx context.Context, in *CollectMacroRequest, opts ...grpc.CallOption) (*CollectMacroResponse, error)
	// RetrieveRAG performs RAG retrieval with the given query parameters.
	RetrieveRAG(ctx context.Context, in *RetrieveRAGRequest, opts ...grpc.CallOption) (*RetrieveRAGResponse, error)
	// ProcessLLM sends the assembled context to the Processor LLM.
	ProcessLLM(ctx context.Context, in *ProcessLLMRequest, opts ...grpc.CallOption) (*ProcessLLMResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) AnalyzeTA(ctx context.Context, in *AnalyzeTARequest, opts ...grpc.CallOption) (*AnalyzeTAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeTAResponse)
	err := c.cc.Invoke(ctx, EngineService_AnalyzeTA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CollectMacro(ctx context.Context, in *CollectMacroRequest, opts ...grpc.CallOption) (*CollectMacroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectMacroResponse)
	err := c.cc.Invoke(ctx, EngineService_CollectMacro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) RetrieveRAG(ctx context.Context, in *RetrieveRAGRequest, opts ...grpc.CallOption) (*RetrieveRAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveRAGResponse)
	err := c.cc.Invoke(ctx, EngineService_RetrieveRAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ProcessLLM(ctx context.Context, in *ProcessLLMRequest, opts ...grpc.CallOption) (*ProcessLLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessLLMResponse)
	err := c.cc.Invoke(ctx, EngineService_ProcessLLM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// EngineService is the gRPC contract between the Go gateway and the
// Python engine (Module A). The Python engine implements this server;
// the Go gateway is the client.
type EngineServiceServer interface {
	// AnalyzeTA runs technical analysis for the given symbols.
	AnalyzeTA(context.Context, *AnalyzeTARequest) (*AnalyzeTAResponse, error)
	// CollectMacro runs all 8 macro collectors in parallel.
	CollectMacro(context.Context, *CollectMacroRequest) (*CollectMacroResponse, error)
	// RetrieveRAG performs RAG retrieval with the given query parameters.
	RetrieveRAG(context.Context, *RetrieveRAGRequest) (*RetrieveRAGResponse, error)
	// ProcessLLM sends the assembled context to the Processor LLM.
	ProcessLLM(context.Context, *ProcessLLMRequest) (*ProcessLLMResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) AnalyzeTA(context.Context, *AnalyzeTARequest) (*AnalyzeTAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeTA not implemented")
}
func (UnimplementedEngineServiceServer) CollectMacro(context.Context, *CollectMacroRequest) (*CollectMacroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectMacro not implemented")
}
func (UnimplementedEngineServiceServer) RetrieveRAG(context.Context, *RetrieveRAGRequest) (*RetrieveRAGResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveRAG not implemented")
}
func (UnimplementedEngineServiceServer) ProcessLLM(context.Context, *ProcessLLMRequest) (*ProcessLLMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessLLM not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_AnalyzeTA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeTARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).AnalyzeTA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_AnalyzeTA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).AnalyzeTA(ctx, req.(*AnalyzeTARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CollectMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CollectMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CollectMacro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CollectMacro(ctx, req.(*CollectMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_RetrieveRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RetrieveRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RetrieveRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RetrieveRAG(ctx, req.(*RetrieveRAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ProcessLLM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessLLMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ProcessLLM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ProcessLLM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ProcessLLM(ctx, req.(*ProcessLLMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeTA",
			Handler:    _EngineService_AnalyzeTA_Handler,
		},
		{
			MethodName: "CollectMacro",
			Handler:    _EngineService_CollectMacro_Handler,
		},
		{
			MethodName: "RetrieveRAG",
			Handler:    _EngineService_RetrieveRAG_Handler,
		},
		{
			MethodName: "ProcessLLM",
			Handler:    _EngineService_ProcessLLM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine/v1/engine.proto",
}
