{{- if and .Values.mtConnection.enabled .Values.podDisruptionBudget.enabled }}
{{- include "mt-node.preflight" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mt-node.fullname" . }}
  namespace: {{ include "mt-node.namespace" . }}
  labels:
    {{- include "mt-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdb
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mt-node.selectorLabels" . | nindent 6 }}
  {{- with .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
{{- end }}
