{{- if .Values.mtConnection.enabled }}
{{- include "mt-node.preflight" . -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mt-node.serviceAccountName" . }}
  namespace: {{ include "mt-node.namespace" . }}
  labels:
    {{- include "mt-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default false }}
{{- end }}
{{- end }}
