// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_RunCycle_FullMethodName         = "/gateway.v1.GatewayService/RunCycle"
	GatewayService_SetActiveSymbols_FullMethodName = "/gateway.v1.GatewayService/SetActiveSymbols"
	GatewayService_GetActiveSymbols_FullMethodName = "/gateway.v1.GatewayService/GetActiveSymbols"
	GatewayService_GetHealth_FullMethodName        = "/gateway.v1.GatewayService/GetHealth"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService is the gateway's own gRPC API.
// Used by the dashboard, CLI, or other internal services to trigger
// analysis cycles and manage symbol selection.
type GatewayServiceClient interface {
	// RunCycle triggers an analysis cycle for the given symbols.
	RunCycle(ctx context.Context, in *RunCycleRequest, opts ...grpc.CallOption) (*RunCycleResponse, error)
	// SetActiveSymbols updates the user's active symbol selection.
	SetActiveSymbols(ctx context.Context, in *SetActiveSymbolsRequest, opts ...grpc.CallOption) (*SetActiveSymbolsResponse, error)
	// GetActiveSymbols returns the current active symbol selection.
	GetActiveSymbols(ctx context.Context, in *GetActiveSymbolsRequest, opts ...grpc.CallOption) (*GetActiveSymbolsResponse, error)
	// GetHealth returns the gateway's health status.
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) RunCycle(ctx context.Context, in *RunCycleRequest, opts ...grpc.CallOption) (*RunCycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCycleResponse)
	err := c.cc.Invoke(ctx, GatewayService_RunCycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SetActiveSymbols(ctx context.Context, in *SetActiveSymbolsRequest, opts ...grpc.CallOption) (*SetActiveSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveSymbolsResponse)
	err := c.cc.Invoke(ctx, GatewayService_SetActiveSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetActiveSymbols(ctx context.Context, in *GetActiveSymbolsRequest, opts ...grpc.CallOption) (*GetActiveSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveSymbolsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetActiveSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService is the gateway's own gRPC API.
// Used by the dashboard, CLI, or other internal services to trigger
// analysis cycles and manage symbol selection.
type GatewayServiceServer interface {
	// RunCycle triggers an analysis cycle for the given symbols.
	RunCycle(context.Context, *RunCycleRequest) (*RunCycleResponse, error)
	// SetActiveSymbols updates the user's active symbol selection.
	SetActiveSymbols(context.Context, *SetActiveSymbolsRequest) (*SetActiveSymbolsResponse, error)
	// GetActiveSymbols returns the current active symbol selection.
	GetActiveSymbols(context.Context, *GetActiveSymbolsRequest) (*GetActiveSymbolsResponse, error)
	// GetHealth returns the gateway's health status.
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) RunCycle(context.Context, *RunCycleRequest) (*RunCycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCycle not implemented")
}
func (UnimplementedGatewayServiceServer) SetActiveSymbols(context.Context, *SetActiveSymbolsRequest) (*SetActiveSymbolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveSymbols not implemented")
}
func (UnimplementedGatewayServiceServer) GetActiveSymbols(context.Context, *GetActiveSymbolsRequest) (*GetActiveSymbolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveSymbols not implemented")
}
func (UnimplementedGatewayServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_RunCycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).RunCycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_RunCycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).RunCycle(ctx, req.(*RunCycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SetActiveSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SetActiveSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SetActiveSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SetActiveSymbols(ctx, req.(*SetActiveSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetActiveSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetActiveSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetActiveSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetActiveSymbols(ctx, req.(*GetActiveSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCycle",
			Handler:    _GatewayService_RunCycle_Handler,
		},
		{
			MethodName: "SetActiveSymbols",
			Handler:    _GatewayService_SetActiveSymbols_Handler,
		},
		{
			MethodName: "GetActiveSymbols",
			Handler:    _GatewayService_GetActiveSymbols_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _GatewayService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/gateway.proto",
}
